apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: redis
type: Opaque
stringData:
    redis-password: ENC[AES256_GCM,data:fqsZ0D5SJDgXGk3zOgQjeb6qzApOtbXr9AP4lM5zXw==,iv:IruQ0qft+GNAw0E8nLuIWM46A6jK1KE4l7nboIFjzDU=,tag:05/2ecZunufgxqkP/OqerA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdTAxb1JsM09rR2JzQW5G
            akhRbnVhQ001d3dkTWYra1FBMHRXU3JrRVZFCjhRWVd5b2hJaU9heTNmMXhidkcx
            ZVpyRzF4OThPcndtRWszN0xvYUdXRkEKLS0tIGxUK3NReHlrcDhLTU9sMXhheTAw
            Mm9Cd1JqdGh5aGIxUDUvT0NKUzFicm8Ko9FTz1ayoapGsjD6Yc5Xm2ouQQ+UqtTK
            IcIKwIggRQAkSa6aI6M1Q4eq8IHFvmvLWWcg7hWhXPkEqiIz909lPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T00:40:06Z"
    mac: ENC[AES256_GCM,data:zq3PdXFFwsSMjfhmiJM0CF0A0nWskoV9gR3jzrAMhZKbSR8pyn8GuanXqIURng3wUWVhqGvigYmt8LB+iG2FGpIJU6cdv9YFGq5D83kVfeEGJxrKzWFUbBOemBXQ0UjWnRlSv/ChtWliksjS0VF3/QgjP9SRRcOXcorEgGZR8+Q=,iv:Z1L5MPkb50EKk+ESvggulWSiA57+3lHUEA+nL2C1O7c=,tag:9T0aOt/zN06OQheHHVxHPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
