apiVersion: v1
kind: Service
metadata:
  name: grocy
  labels:
    app.kubernetes.io/name: grocy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: grocy
