apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - ingressroute.yaml
  - metallb-podmonitor.yaml
  - servicemonitor-argocd.yaml
  - servicemonitor-emqx.yaml
  - pod-restart-alerts.yaml
