apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emqx
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: [mqtt]
  selector:
    matchLabels:
      app.kubernetes.io/name: emqx
  endpoints:
    - port: dashboard
      path: /api/v5/prometheus/stats
      interval: 30s
