apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-datastore
  labels:
    app.kubernetes.io/name: changedetection
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
