apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teslasync-native-api-direct
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: "Host(`teslasync.cyphers.app`) && PathPrefix(`/api/v1/`) && Method(`OPTIONS`)"
      priority: 1000
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: teslasync-native-app-identity-strip
          namespace: teslasync
      services:
        - name: teslasync-api
          port: 8080
    - kind: Rule
      match: "Host(`teslasync.cyphers.app`) && PathPrefix(`/api/v1/`) && HeaderRegexp(`Authorization`, `^Bearer [^ ]+`)"
      priority: 1000
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: teslasync-native-app-identity-strip
          namespace: teslasync
      services:
        - name: teslasync-api
          port: 8080
  tls:
    secretName: production-cyphers-app-tls
