# =============================================================================
# SOPS — age encryption for secrets
# =============================================================================
creation_rules:
  - path_regex: .*secrets?\.yaml$
    age: >-
      age19ksrgufl4h5h2ep6wlujkt40cvyay7jrryrv64t8w0pel6yvjaqqeyctxe
  - encrypted_regex: "^(data|stringData)$"
    path_regex: .*secret.*\.yaml$
    age: >-
      age19ksrgufl4h5h2ep6wlujkt40cvyay7jrryrv64t8w0pel6yvjaqqeyctxe
