apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secret
    namespace: freshrss
type: Opaque
stringData:
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:7VE9wcE+HMIhPtm1CDnUU62VENnDnKHx1CfANV8cPYmTD4iFkwywveWr3lCCVlJ/2LQRTfGYxfb7g0ZtcgRk5w==,iv:9zLJkgweUyqChBfl79PGhh9EWz2t7kH0mWVC+SI+LVA=,tag:U1AWnttItLZOWalMWUWJ5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a1Qva1RSZHUwUncwdGtE
            YWtPWkxHZ3haOVFMTG9YbFQvWTZiV3JwYWtnCnhmdW9PbkhZcFJ1R1ZKdVZtN2h4
            RXpIcG8vOERrSUhsNVBFSjdkTE9nd1EKLS0tIHhHNVplT2RGaVI1SU1tS0laK01F
            VnlXMzZxSXhWQkVmK0dUOGVFSU40RTQK/s6HU+n7zqU0AZWLB3JbgF/08QJDt97a
            kTQ8qa7OCmT64ScJrP633SdiLSPq2aulNNRf9nfF5/6TZxP9G+M1fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:52:08Z"
    mac: ENC[AES256_GCM,data:6uUSAEvQNfm3rtNWh4ukr/Zrok65HtyDglNPEzABIE+lSCZNdKa4A2ONb+CDdmFMK1qBpmqqB+6uwS9cobvNPrHpU+x+T4vg/4uTskEtODtOp+Lw/BgWx8XLG4+KixRhmcq84kDy018lZ1IhDMYKCm4bWg6Mu3QrZP5uRTgAc0Q=,iv:XAEArU+zRpDCH3F6deClDTJaBs7Q6mAojCKP47a44bE=,tag:kBwsk7JghVRyYW13Mq6/Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
