apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Home Assistant"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "home-assistant"
    gethomepage.dev/description: "Home Automation"
    gethomepage.dev/href: "https://hass.cyphers.app"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hass.cyphers.app`)
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: authentik-auth
          namespace: authentik
      services:
        - name: home-assistant
          namespace: hass
          port: 8123
  tls:
    secretName: production-cyphers-app-tls
