apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    tunnelToken: ENC[AES256_GCM,data:DrlS5QebzhiwWgZwcFj6QFUBJvsUKuI9fVi/Mafe8ZRkNo4UPC6FZJ6U3WH6N27xfwfynDTLIaTZQII/MD8DCEgFNqxQnqXNpykq08Uc4oagQYYot8fEv4hS4Dn2HO6ua/1hsGKsx0vmxKVyQCI5uRSavMb2IXNuM1fPaZAjObL8iZbeh/djbRQY3Y9E+OYYdehn21W3owhGUYmF/SmJgBZA21p+4oufCeLPC/Oh9dt0cIvjq42NBA==,iv:pF0Fp4HFUqErlNzROUx+SFf+vRXYihORnCqjaZV+s/Q=,tag:V8mfxCLU8CnfjaD6wzt8BA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSUJXem13SWpnWDZ4QUlj
            NTVmbER0bWt1Ull5dDcrNEc2aFFRN1FRd3dJCkd0MnJqN1pnQzUzamdEbHNJdzBy
            UVl1VEVIVm9BaVhDNFNqZ1huNEhiYmcKLS0tIEx3QmkrM2hFQkt2dGZSVXRCLzRJ
            dkpUMC84TDI2Z05XbmVFYmlLcW5rZ00KkyuKPdgXUpsadw1bGZ2nEbEUKOXXy2sL
            bjOhcraFB2CZWppX4pavW98F/gLJUq7R5C0oSFLdb3gBFQseAwNF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T00:10:45Z"
    mac: ENC[AES256_GCM,data:wQ9HbewB0xsyErVL+BBGsA8hLyaCbRg46LftKaesjBQfzmvf04UCfKXsEKW+sfL81Ljw98KJ31yBND0QRFVTlSR5VPzT5dIysWZgsQh696u+gHLkVLvN9zgFvyMWZsQHy7GwsWKTp+vfPHiVlwNY/sLSUq+hsiFfM5NFOnrOKlU=,iv:Sqt9AjorMba/7CeIc5zYiiUPEUJmktWnaAq/mZM/5J0=,tag:1qfR4T/Ma6SZZVoHCTbGJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
