# =============================================================================
# ⚠️  PLAINTEXT — Must encrypt before committing!
#
#   sops --encrypt --in-place apps/authentik/resources/secret.yaml
#
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
    name: authentik-credentials
    namespace: authentik
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:J9L0f0IIR0im7x/2QukelhH1qYw5j456jSgMNhkEYA++OZbH+esb9tuQN8sfMm4bBkm5/8pG1MZcnTd6YBa9nw==,iv:ioMGSR02u4JWn5HKbZ8Gc9XU2BGB1iWJ7DewzysMoaE=,tag:67cwiUERnCdVG9fR4NMPNA==,type:str]
    postgresql-password: ENC[AES256_GCM,data:ICKuGw4Suxuj,iv:VvZeFfo6E+vsZhBm17FlMOfCgRLxOHQtcoMGbEuWDYk=,tag:feYrJKQHPbVSNU4OQlvlCQ==,type:str]
    redis-password: ENC[AES256_GCM,data:YSo5BdynDjHFbkhRCZreJNasPvvDJ/lT1ExZrjNouw==,iv:EqPYIg7y/8hqEfca5QYEp8jkpWF1tQpe1uLq6CHFL6g=,tag:LO/fZNXZVhsC34WyeVgo/w==,type:str]
    email-password: ENC[AES256_GCM,data:R4HJ9uiQPvQt/ApUKDTlnA==,iv:tGzEfe+qHduwSc5VZbIti8+JiDuvqZI03FoqqKGaqog=,tag:96lg/W+dt7mJ8kjtbBg4Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUhxOTdvOFhiZitUaEdJ
            WjJZeG16WHhwL20zdm9aSDVnN3orejNWOEg4ClJCczRvU095TUlOa3RoNklBdnV4
            Uy84bGVzRlcrakN0TUNuWGtjTFFqV3MKLS0tIG5ESTlIY3hmK2RPMGNwaG1WOFpi
            MlJpSkRpSitpMXhQVzVya3UybzdwREEKybprrS1DaNr/Myltqnprqqt3MLvNoYfM
            scg5KH4K3nuNrj3mLAa043tV5zRUrkS4Jivlp3FGHTM3rYRBh6j5pA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T22:06:33Z"
    mac: ENC[AES256_GCM,data:GGQAyGp6ATwmv3TA/+j+t/gehbhAgmVgx5Y0YN2G4C9nHOhUjemeE1P02guUwqm4Oue+hLeplSPk3FaTlumAfKM0jpHo0iiFawqZoe2yPl2MRybDZ2hMO2V8MtBSmBFnEFeMxfYjWwGrFaR41rHVzSeTgADRAB4MfKRHc1F+iDI=,iv:QiWoDv+Xg8Y4rcsWrnb6dLrpBRfqU168KU5qqLlrmm8=,tag:sFlhXYfJotqNrX824zLOGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
