apiVersion: v1
kind: Secret
metadata:
    name: teslasync-dev
    namespace: teslasync-dev
type: Opaque
stringData:
    DATABASE_PASS: ENC[AES256_GCM,data:5rxHHMV+yJXCB7KDUXMD1uDZ9ba358i2eC+p06EfXso=,iv:S+dbmCtWmJQmioV3gMRO0tIZGJHkoBzQLjDKHafQXP8=,tag:W96YNkDabqJUsyfmspKg0Q==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rgmC/UGELmtir0914wK5YtXg9+AMpMkraa44EECq652nw+oiu86AQYWiZHg=,iv:6csPm0ubU+Adql2Sv7OL0ewsrlqYi5HqldYp6Zasv7o=,tag:TpayD8AdxGww5sn4lc2DFw==,type:str]
    GAS_PRICE_API_KEY: ENC[AES256_GCM,data:A7ttSGB3AZowd/TXjqZmVn8i7ml659v1ZlW163dMRqDOa5D/FPxOQQ==,iv:7OxzGPYtpWDWtChM5XH8cvPVFOPjRZUcoDjAyZRWIcA=,tag:rbvWEJMRbNIUY5AZaKkeLg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3oN/6V4xSSrY3shRIAjPfP96LbVXEWckr9RB2p20IA==,iv:dkyWVs/t0I28IzPJvyh57HLi4tMpyZbMlutFJWwi+vk=,tag:ZpFCg4KdkJP7LiTHrNwunQ==,type:str]
    TESLA_CLIENT_ID: ENC[AES256_GCM,data:BfsNXkHRMaA8OR0OZTftqXctzZU9cYTZgK3ElPCspv77f4/r,iv:EemVACfiR8zwOfcsNA4U54J1a+zg271KlQFtU7MQYR4=,tag:mvYRx9I86E/T7zbv72SsJQ==,type:str]
    TESLA_CLIENT_SECRET: ENC[AES256_GCM,data:XDm25LCy7o1ViqgjXFEyxmw29ZF2JD8YsZ4=,iv:fjC6bedIf0BKZajGXNp8j+F8bg5oqx1oDAy95cv34RY=,tag:F7eBx96Z105JctE7BqGEbg==,type:str]
    AUTHENTIK_HMAC_KEY: ENC[AES256_GCM,data:0tnwV7ZnBoSutKi7M8ShLwQ3shNSP57XtxIitfdwE2izR5WSxo/FY0d4BBklEuHiDYKLhZGpAY0SBKxsV14qPCQnRRuhjlp3XZq5ApD7QfqT1XCL0NBglYunJ194ouhrUiiITmg+dQYRVMPJOavws+vZbr1YaF9JDc6AH0BYna0=,iv:l0StXFVpzcG2JYed6OZvXkFem7Fp99WhJ4EIjF2Po9Q=,tag:vcAL/U1YlVGw6QWr2cqKTg==,type:str]
    AZURE_MAPS_API_KEY: ENC[AES256_GCM,data:H5DjWUtFxZ28Rh1vC6QUhp2Cunp79gj9/nI71KS4oz4KSbVwV7hmd3hqJSPlM5zgiV8rb11q6ZNV4dMwVh3uTyavn6F/ClzxcTMWjEJ92aKX/a//,iv:g9UjUFv3Ll2+s9FREGcrzPYuhXsaX05ldzicyMj1xdE=,tag:iJjweBmsY0tdcdyYQw3Oug==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:pDo9DeJEb+cPKD8ERwQ9+d4mpz08k/qYPyp/MRbZlgVWx8lhQJ4miB70dVvzxBwVIasM2M45kc5Hg/GxWEOYZKfU2iUDOCgznhMsYzmKIug5w1eQzufNRoL7AFSmpqTNB4Go0ePeJyCRPA==,iv:gtr7RQwHzqCCtprebtJOqaedJx2BQeKiW7RpBYIlcVA=,tag:n+/hQ2Yoe4/CCqlhWy481A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTUhnU3pjWlRUM2doeWM0
            T3BYSmtDNnBib01vVFQ4TGEzSDlYdi8wSm1FCkkyVUxxRytybmJvZVJ5dEJ6NHkv
            SlNsT3ZhdWVCbUg2TS9jNVFGVGRwQ3MKLS0tIDZaLzdIZE02UW9CZFgwYlpGSUxo
            ODZFWmhocHRIbVpINjYrL2xydTlSMkkKJWvTEMQmwt5qChy+T6jcoObwg8MAGzBd
            WmKEytYr2HPh2WJ+c85HnzgNexAzvg0sVF0gUDvLqTEQbN7LZyn+Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T23:49:39Z"
    mac: ENC[AES256_GCM,data:CmmQu9xRq6DyOo2a2CSMcG+K9obH8ktnB7ocJOhEoerPDPBjcW+vx+b3VLEQ6hs/m+kZ+uUUo4FXAH1h9C8T/v9RDt4XkcYLcAbDYOMPQSs7e9U1k9oAO0WlYIbz5huXJOE/L0iz5pgRXFhRxZF4dXRfcOwcmCy49hEdtAEZpxg=,iv:Uu7KEZ9iQXFp1yE6ZaZ3Ut9dYwX/9fmHD2Y7rhFh5Xo=,tag:VBXF/fPYmkgkJlrbuFaUNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
