apiVersion: v1
kind: Secret
metadata:
    name: outline
    namespace: outline
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:+yLMTy4+kamaZuw7HCHczjk4G10ZGzyULrgSXWUUIgvEWliGZgq5uxwr3LpodjuZQr8SRIlmX/1uf99nJZ5kXyXNc2qMwTqOuCf2XLhUdL10jNsomtWwUImVSSNs+uEWZjIc7K31X1vKhG8=,iv:2HYfr2CeUoInIvhHXmC1Ahu0QejngKFRJPwC+7AkxY0=,tag:0pBPS0Tbj4ll7o+sD6xgtw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:5Yx2a8+qi+KU4hNKfwPlYBLWoGHVvwAhrM73iuQHyT894tiDT/vYDdXVB+7Qs96LmuHFrj7rmedCEPh/kuEJfTkp0pSgrgaXJ2gdMrn3TiMn7g==,iv:WYML+bKwr5WWs7GEPV7vIBHJlUMNo4gB2WkoiWthMPw=,tag:R2cLs0sr9B2bavoLrotNxQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:g9BniCAYJxXSy2ddEIqufhQjlI3PbTCmCzGVKU/X4T2J/kIQGyFFJw==,iv:Mz1VC6JiAoJOtKVDM3d38SxKsoMlGNT4tPD38fsvd2Y=,tag:zG5ljZ2DqLxFq4fJThaV6Q==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:PWhNY6LqekLzY7XvS8kkMfDcaaE1HQ+ubJB+ddO/blY6HXNdb+mYYpRO2vCBopuGv7h0QZv3b/tJuc8bLtKaGD6czH5VLLOhvFjNbdcfXj0sCvW3l3BpM1wkgMt0oqKfgFnmh3doVUUmG4TpxPOA/EoNEBQnKM8IhZ+KdtRTYAo=,iv:FcT8KZrq7FhLUd/GxZF8L11iYOjRvfkGqFUtm2igJps=,tag:YuRTsGL2UW/aqESmrxzqrQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ajt1/owwEMm3c0efT2atyfVhmyx4lXKt67KvsiQ/uuS/zRGrdl+GVhZfyywvGMTfaOp7zn2Ct/OjZKlHLRn0lA==,iv:OsNimLGZadJ1FjAXs+sFX9rFBDDyoQTe6qMfO4+UGOg=,tag:CrO77S/RmEth5iAYAiY6GA==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:7wJm9bvqe2AVeflq4zwpoEDvqFUAjQewxejKZRyaotQE7DKcrfLOqto+m3rskTHZa915I4k9rqE4jw40m2hdlw==,iv:lVUWmuVCdSK+6efBgjKCcAkW9HAxzEZt/oo9m3DwiG8=,tag:Zto5ZEMWV5hyu8ZOVqICKw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:d77HqSlNrf1pOuat6h5yRma27ule0cCwDD4R0/uxrS3xibSDm4lHF7uAC4H8gLq6wW7F2kjWEz97yWf4o95VCa+LF3l1,iv:Yy4b7jEICsUleCymdz6I90mh+h+aI1KqSXh3On2MX0E=,tag:ipQCRiLpb8nTCDXfJQN8IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOVVRWXdZMjFjMGI2YXJa
            cTdWRUhBaTRjcXZqMkkzb3hUZlVZbVprMUQwCk9hOXI2UUN2bEwxQ3Mrd0xLc3k4
            V1VKRzJpODB6eldVWmxJcnpoT3pydm8KLS0tIFVDVkdrT2JqZ2J2aTlUdjU5NmVX
            T0wxNmJLVGdtdXVxcVZtZWpJRVlxVUEK/4pdWyfAN9an3gSosDxk9NgFDiJNpD4c
            yblR8RNis2jAxemkoyiv8ldTkhanJEb0d9ICS3Cv+Fd7y5kTmqrR2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:51:33Z"
    mac: ENC[AES256_GCM,data:ciGZtkFpw2PXcokeMIBEsr6Zou0ap8FiEfc3VzB6Hs5QeE+ceC0G6LLmQZlt92DNSnT4muOxvN19qwJfoR/1gmWmRtTSD4pawWYOkqyOwkSdVkcXKSU6MSMPslswQodg2WJg9J56jRRH27oiY2RDEtzS4yu4MPfulK3lIDL3uVw=,iv:07qzOYgx8bvXxx28SF9QjQ55VmeBYZAUoaMh9zfuFcw=,tag:Jb0b/FL26580vR6r6hatrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
