apiVersion: v1
kind: Secret
metadata:
    name: outline-secret
    namespace: outline
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:VPpZSi0rvfh7AhAS2GHx3hK8YBQNZgRkX7ZDR4jWsogGTspixd0P1N+kSOJkBo2sngooTQis/JpO9ji7mBdglJjpqQ7L1aiNCrGaD6it/9eo2uZAlmLZSZI5bCRB2vx8T9MhpWhjrpujhT8=,iv:YoDZTzM1gyT1h39yhFEhGlb3pwlHUKP8QqDAWDRe7po=,tag:ettV577HhL9HmXfcMiRXjA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:CDvOKOnjt+DS1kbm6Yuzy9++CgCbr9hTo6B7lbKO0u0DJlzLQjyq8JRkwwiHTBOify5igwh9Fp9Xi70+6yt1OH3UKz15ARWlXv59Yw5T9WwOMg==,iv:FhfJMPjYDvKQ0IF3jfavgKJWrNc4G92iByRMvecLe5M=,tag:CQvW2LPgBprE5DpxrNmePQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:gCR9lkm7BgsCpC0zcjG8GySUeVXZQayG4OrI2K6d++wBO8fDTKosIg==,iv:rNhk9DG1C8GwAhLelPJe28FrAs6HJFESCAzf+lWxWUY=,tag:M1oKS6Y1SIWAbTb8tZHX2w==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q7KEdPxmjrr2JxQjmJqMnPlPCoPifoUp08ZYMLQ9e8cR15WBYPS7G/LgRssosmsPMfB/f9p+RJZZneXT5PdU5Kso6eFBIR479+nPbrc8az+ao3UIz64APoGXMBYySQ9KKIbckBMyg1+U8MSyfjsqOQ6IBZ4a6EuELRiTmgkOwAo=,iv:lWB8GUEKC9e2nsgIxETFJfPLCRl8P089GoW6MIqYJZk=,tag:DOK9EL0hckZPFTffci46sA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:5fHzmiUaH7eoVrnOxxIRBBnh3P7rYt6WoIaOZTayUT/l4u00Yfkw/i2d8jFJmp961IRJD4rgoUaAeyiKlk5j7g==,iv:v1Jp/hTM90+dhmh+ixOI0s81kZuKZvUzIIilftgwG/w=,tag:BizhSU5g4g47OB5j7chnkg==,type:str]
    UTILS_SECRET: ENC[AES256_GCM,data:ZBYygdnbGqNNMOCMg2xFqsxtgCDxFm8XhMbv7mjuxACwruD/VIVj1S3XSNq1G7pGFsFKbWUopZMISJKp3AjEQw==,iv:anLCQdi3tvevIwaQNC34BU/79al+DxebZEa5uByUxAQ=,tag:VqfRebXa4uKGT1ijjmylog==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:DXX4GYNVHoiO8t658Xwq+ncTAPg7UCfcedQY4u4JYtFLbHuR4vr98iqx6/ImxUrrP2b8u6PSUF8PmpQfVZwVeFBSCf2p,iv:1sijLJ/tmSjDUGYQdX3Lxu9pj6B9xrMo0N3y+j4pEZk=,tag:pWfhqRwaO75jCuy3iaY0Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYXlDUHE1MHJpQkgrYTYw
            ayt3dGZlS2pNNHhMRlFVeGljbVkyNnpMd3cwClVrR0dJV2tsN0Ywa3FOQVBTMk9B
            d3JDdlR5NzlqUk1lRlBWWTdtUHkzM28KLS0tICsxT1VoTUQ4VHpxc3RKTXhRTEMz
            REs0VW5RWEZhNWRheVZSK2NvVlJ0VHMKWv1YP9mZiTeLAPS3ekW9x4dQhsSMoDXs
            C8ei0k3h2fZTgN/Wq2myElbI8AOyW3BDe/67KrbliHdt/Dxvj1Ta6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T00:45:19Z"
    mac: ENC[AES256_GCM,data:nTJkS+Qi0sDFoMW/Pa8jQBuK6dcdH98Js0rWL0h1+92Gqf8JSMwdfayQ9rM3tFnzOA1TZwj21vsti+KXPozc6A90/8WkiaZB0OfjSEugBIOSyJ9pA27bfsSJOs8BexK5gdxQPd2XrxtghOnIAkPScFHOaUkg1t3X/eD7FPQ4eTg=,iv:baMc7zyGqePOyBxhSpdBMz+3QjEme1zEgrvS19O+JJQ=,tag:0NH9pK9RpifS19Dt83kN9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
