apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:zRr0oqTbzBg/6qN7/sXCSQ==,iv:IeXncEDyTGu9qHChZs2Q05uFc6WyIOKAwuJlU3mm4KE=,tag:d3mRfbwy1MP5bPusxpmZkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMkNUVmoybnF1VHFOd3px
            RW9Hd1JkL2tETThXaHJOQ0t2cFdzNGJ3ckF3Cjhka2VGY3BXRGoyL3pjYkg5dUl3
            MENNaDRxUVc1UzhUZjB6RjM4VVcrZ28KLS0tIDF2SGEzM0tBbTgwYU4yTVU4aEZ0
            QkpBbXU0TEFDN29sRm04R0NGWUhmSWMKiUcSeVKDyOF//vPbHlYALBbf3a9mWsGl
            4+Slrmw/TgBq5kZ92nvXlpFc9GDJatKzcOkvW6uRU0s34s71YAuETw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T06:43:53Z"
    mac: ENC[AES256_GCM,data:8ppDRGWZN6irgNbojde3JONDvmpPeLlR+NC4Ym6enfCAkj5FjR7P2wXClnX1yGiwzFQP7KMkVZdZ7j07n4UctVNCo7Oed1f5CM949LyTrQ/tb6cmsT0C4h/WfMzxrpSIYygGD4HqHP7Z0MAI7OOVRTjQav+T2oK0wEMWM8uB+Cg=,iv:jAMVNr96QRX/LHazQYNibuZM5QsIRV7kaNc6VSdTzOo=,tag:G9ejKhWpzNTY63iop4XCdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
