apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-insight-data
  labels:
    app.kubernetes.io/name: redis-insight
    app.kubernetes.io/instance: redis-insight
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
