---
apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  labels:
    app.kubernetes.io/name: nut-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9199
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: nut-exporter
