---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nut-exporter
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames: [nut-exporter]
  selector:
    matchLabels:
      app.kubernetes.io/name: nut-exporter
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
