---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atulmgupta/-k3s-gitops.git
    targetRevision: main
    path: apps/mariadb/resources
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb
  syncPolicy:
    syncOptions: [CreateNamespace=true]
