apiVersion: v1
kind: Secret
metadata:
    name: echostats
    namespace: echostats
type: Opaque
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:FbQiraRp78U5cSyLd4tWUslZf1dXXL2QuBt/xa3XKm0=,iv:8UsOm/DnjTIeqQH+9airGt6f5mH4cZLyFieC5t51g/E=,tag:61brFNq2imbI7U7NW7PgHA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:hli5rUcT/0KcAo2VeHFUH1wUw33FzKWlCErVZBRtVgY=,iv:0Gjoh0e0qlBWfJlMBQixdUHP+j4EM//shacwgv7feVI=,tag:GNNIHaW2pvEQGCytB87OHw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:6cEuGJvkS5+EjXevhru5mWuW0vfczXwzxYXnRSh7f/HJcQFvmCtJST/o1y5DhNaCU2+KNEoWpXaCWqDs7ju/eg==,iv:TdflWbOY6YkQXBfzbNE042eN8ONTsmmfpn4OaL1PbVk=,tag:byis5BzpqhRT9iV9YphrMA==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:0Alv988uNcqwdIeF9NxmKtHiBfB+tdizwlecZe1tkMSqBGvSo4dOgrf+0ce76CqTfnyn38IMfDnhOEppXhdI4w==,iv:dMxq0CRoOKdwpuhRqLXPizkzzdW7FQYrp8z/21S2mR4=,tag:VF3gdWAHY8yySV+/inTqNA==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:gCGK5nWo9pz0poKbktsZr0GsFhgIzaacXu5AMWAUpFtt2mhsSyz4Sk7IAVPEo/28tawwuBOJtLUbZDF8Q4ZIHOP5fyt71eK971UB+Qm9BEphT3Empsp2nJ4UB3lpyvHf8oUdLyO7ITbw9SOr7ryae/NGskTRZxQaZpo=,iv:skuqDk96V3HUFPCe5Gb8+FYniSWN0TuPKX1b5Uin+Fs=,tag:h2a6sAi1tfxfnO0sirQ4ow==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Ola5IQu/JQkxhRQCwMXUq6OPukKv+kN2oIEGsfg4EjRPD1/WFBUsXgcHiNp0JwmpYCWMxnedVxMq588xauLyul+dzpAgP9BuBR40A5dmi7/74w==,iv:X35KRRQLKyWEGLv1/0jKEQzic8P//JCe5tYGjGDaj24=,tag:J6+zq9j4/VVnIfM4l0wxig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTnBHL29YUE40dGRjRjNU
            bGlnUlVQM2p5TElvVFFyL1hhSzBEWVJYL0IwCmhhRUZUV2JaY3ZIL3YwMG9ldC9x
            SkZXbDNLei82Z1JleU10bXIrS2ZRZWMKLS0tIG5HblVab29RaGNOTkhOcmJUczE3
            ZVN4dXRLaWFsd0dVbzJvTGFWVjNGeE0KVWzeo/LYnfZffnWzJ4tZaI+eTaz84EKF
            RKqAN6cwsrT2SAkvM3M+NsNrrVcSJ9dYj4gPR9ZQ3vfpyqg6QNKv/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T12:48:25Z"
    mac: ENC[AES256_GCM,data:hW22W5A/224aMRVU6wf3wqgrQPBXXDbrliPongvcknhjPqqEHSeVVf3s1ZpfT+UDDJezw28KZnzEzy0s0xk5U6pZW9Ls84s7veocmgoCj1Ewy3Egydfgv8ALpCiXjlHB4+mIjS84VBNl9hVRW2Fl/z1S5qHd0WgjmCXIHKNRVRo=,iv:6bQ8xw3I7mrnwVh0IkkZoxq8ywZSyDTzkXu9H6wNeow=,tag:79RXuIY2/pBxCiSRXLvibQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
