apiVersion: v1
kind: Secret
metadata:
    name: echostats
    namespace: echostats
type: Opaque
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:wIlrdgFAwGbUI5nlfiF7CwAmT0e60cEQckjRuC2bz78=,iv:1In20aigyQuzn59KXFxGNWX26HM4hwcbpGdKJboem00=,tag:vsDDFYC8lfCUWtz2ZOixoQ==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:CtYFV5ETn3AOCF8MSZt09CF3Cbu0QgkjntSvYSnJ4xk=,iv:yM+DQy94l6AaPxCb6/urEQWFjAr3E5fhI4U6bN2bwfs=,tag:zhS9SWnuegPpcrDHLrd8wQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:EMQylKamciqBN/yDYKsZcStFC2NiyfNJboXDytWOlhNtVthKyJ9EdyWrxT37RqF1w7WsvApURUkVmkq8gzhBmw==,iv:BSkGqbFcHWDfxJs/lQQ70+oCX5p3Y7VE+juUnCa1tpg=,tag:qdOEfMed08fNBgM2hGdNHQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:rtIDk6uVobiDruuB2bq9RelEiZ7R6rJ7ojIHZtSLFi5IpJr3HhJdQKmhWiLGML/yEn1Ga6U20I9oPqsO1mNAwA==,iv:aZf/rEnTNYvFLBPA/YLHCly4qg1vG0dLcbWCx1UQ1HI=,tag:DPKx81ovDG+Isbg8wUsxtA==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:tmn3/oMkvFHBVvSToOUViR0QIkdIjbxUcNHdbkTAaQB5KcqAk0TUan/p7KE4uF6DqL3gL4dsz3eP1MEe4jPXKP9weH5AEacIWk4tYFJ+05B8vcF4r933hEIkA+xxYqv1qPFRharFGXdjMSh5xa7evypO6wCz5b8tzfU=,iv:NxEgMnlAaPQXB7OUP2E2AhuLrhyegNQweDjCojzXrYM=,tag:0+j2/cfcxq1DD2CUnflHCA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:7ylVexOZg0DKrnttgktEdQEO44jDVgxoRxV/lIFL2lVnkl475an7labOsfmyUlCXo/oluu2r7jun/P+46nttEyjJBa6kWM1QD8Utq7nH0ulfLQ==,iv:7t6udCKcXqL2Q0UFStzOZjcjinsOymVxl/fJaf3u4dE=,tag:jkGBoV7T3y+L/LgsYR3jFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdkFwV2xtZlpuYktKbURk
            ZjdrdjRNcTc3SDBvRG1ndXZhdSs4ZUVjczFFCjFmYU9HUUJOUlpueUJaaU55aEwv
            c1MxdG5TVUk4UGFYL3Y0QlRLcEp0cm8KLS0tIGJ5VmJSYTBDaGFudEhEenE5Y3Q2
            M3BCNzJFKzQ5UE52RUhJdi9CWkw0SjgK+qznSDUo+GfTx9gsUo8fNDYF1hdDxker
            mVEF4uMdOLJ0uVMJt/Kn590aEefhWY52HE1zu1485VE2a5gq+9FdtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:42:28Z"
    mac: ENC[AES256_GCM,data:/hzPC/yXLVwxoEzVleAZnb3NNR7fSgvARKdGFEtZRYopupsNcPXzd41gXhyOCzQsY1Xci5JgrxFwHODILhFaqZAiqnsghd0e4JlrmxKhUEBt2iy8FBichyTyuoOHrKfqUtQnZrzoh50aELMN/B7GIbcVrF7/XMkG4ZsX4vYajX4=,iv:SHf0fo+5V0B6G7R6nXwHhM6GhLcEW7gDhMcN/OvwO7M=,tag:R3eCazl8zg5WYt/kSDmF9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
