apiVersion: v1
kind: Secret
metadata:
    name: echostats
    namespace: echostats
type: Opaque
stringData:
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:aDrkENrHWzCirmGhJ22lrJXtBfzcBYwSwMLOBV1n4TE=,iv:teSXCWkuCMGPPMILudiiS+6SAbMeSg8nIL77zcsbl8E=,tag:7zzVQGR6TdtAMNKAXwlRdA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:a5LiGkccv9UdRwAeNntDVoQja8x7sKBQhZ25YdMwGDc=,iv:7IZooivzIoKVRibfEMOTzlswyrVSfkaHL7gK1lP74ko=,tag:L9/X1UguA6JOBJ4ZuUDb5Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:1UjP+BLiPCnX1UMIEKnKzgnvgQdoZqaMols4c8o59XzHLh2FwIDWpmbNiFPpuRsfuWAsBQiSBVSaeEYmLBTr+Q==,iv:kPNJle4xv+0cOt7umN8yUzsVzf0l4WcytSoLUSV+t30=,tag:6onkI6NNVDRvgcHUrn/lhw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:xbB0obYLz5uJ5iUQDolUnh6piSvYaH6gbRvw3AppTZI0No2tte5zN91SttONRPrn3YJrAxcqMthZZj32WsjOKw==,iv:sOQAlpf8pSHgS1RELSFcgALQrkpAZcdURyTpzSfcCQk=,tag:aVWl21LqxhLreVHELtn2qQ==,type:str]
    MONGO_URI: ENC[AES256_GCM,data:/VGq+4wIuf3h1Pr+T26/wwV63nQkV4YpMy8+8azPLxNOKUbmbqfdToQ/rNZoP2K/W61vLwrxfkxwQxW6rYpWWpVf/LCR2B/8OrZSy2DJaaXqH8AG6jDkengrYw1dBFHAknNrTMOt8KWL9z9dOATaquLqtqA=,iv:7MxLbCi1RZya4eavGVwVIWZCmSPIMcJTDweUauyMqUo=,tag:SwPvclHKZf1Ea3tilUKKGg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:u0kjUpd2s1acylV8ryB9M2JlNtBt2VgdOACmYXOb6bL7ZZQNJiKy4klm+/S5Cn7Id9CgFXzM6RC4kCOJcy1aTBGkd8UgDPkS6vMpTD4JvOSlfQ==,iv:3vGSOB09GUAV0a0cO52+mj2MII5B1oJULn1ahOdaeHo=,tag:YEnvMoeXrI5R7tC+TujZnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTlc5WC8vWmdxYkZmV0VD
            VEZGRzRoSlVmUHFHWndrMFR6WUxjS1B5Q2pZCldTbHprbWlQZEpJaXNpMlBwMVE2
            VFRSNGV6M3RObFZRd0RFYSt4WDlxNDAKLS0tIEFjWVRKU2pUUzZaRkZ0dGJNd1p1
            S1B3cnhOdlFrUm55bGs1Tkp4VEs3TGMKeU+VyW9JQVq/HrodJM9gzsXvtxaYsd1l
            +KYoBSrV+Rt7C1Vsy2R/dZLFxhKJ86LHgDeeNb9vIguDbKoRW84T3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:17:28Z"
    mac: ENC[AES256_GCM,data:izLy1jiNo0c+BgoQrdwVXWuHXCu3VmmgLvXwmFiFbthTiHHiBFc3vHzXWDrvvnn9LBDtutOcuOfwWdlBTkT/E7gR+8stf+Cge3b1kv7dVECLf93VfnnDMoWGhOP0TxQeznY0n8NgfEHXFtu3bQfTMe2NgC+NH+ZdwwIG7DN1eSY=,iv:smKxQLlKDMckWlSS6D04sVqqVSavvDkSZqYHzYyGrAs=,tag:qawrfKxp1Q2JHiLUWkgHSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
