apiVersion: v1
kind: Secret
metadata:
    name: nexus-terminal-secrets
    namespace: nexus-terminal
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:p9p9dftXPWnxd36TU471uu7indWEm/pa4UDNbQLcAf3n+aTqVsxfSfBEeg==,iv:NEx1N+3ZZDBng0fIqkyned0ubxwwLTdX1xAxNA5UOUM=,tag:1hhdH4IlcoOZHlQsOVR9ow==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:TqSibHP7OpkHqvtvwSVtX3bX7sMXf099/oQ6jOipsuFypulNjKbjqwv5Lz6KJt02+zZ7NjXLqDKOax2cGwJ7vrll9/lZBBmZ8R6Cs13rWi3qFYqS947vUauYdkhMtPRIhKsP6QENUkE0YeHJJYpMubDsVsDExZ3XWzBVtu0RL0uFR1XqUmMFWRlcCtPCymv7,iv:D9EFWDAEPtbiB/gVJ4SAaEMnWgqTPo+JUmFidngxQCk=,tag:FUJk8EJMWdqKDmcJNjkeMw==,type:str]
    MONGO_URL: ENC[AES256_GCM,data:5muFg2amiWzppaRzFZ1SCX3+qztpdOJ1pwCCFJIA2tRtQcJKu9wZ/YbLci7OyzSvQ3GQ/Ts1imMpEo1tZiXe27dkbxdKxZr3TCPZBXaJ7cLjZmMq0eSqCpG320nmqNXJR9J6K3R86M2G,iv:ft0Lf08HMpmIbPDv3gSfgHZLmvx4JJqiPoPaWM/6keM=,tag:qWih6TmRK1cUfHVp9c+xqQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:6aRBFFuYC3uFhzix1jpxDXLJZJ6GkKxl5/W1gfCF8+cRyNvHQrSjRbWkmxaDIO2WeBjuxl6/b6j0sD4lGzZwx4g3h772NlaoZX0rzrjkVLHQwuys,iv:aR09ZA19Hpwr1wWTsborkQxbNdfskDbynXKYV42iGBk=,tag:ssdFjlfwtYZ6EUgi5CAdhg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:t4kmJo3zx9stc/8lGXc7RN7GZvq5bfSWA8nzrDj9LeGYqoXPnqHKWJb+9w==,iv:zzZBVD6WQZPvXX8vqWt1pj65mOFPngCLOXmcnfBTqKU=,tag:ffyDxgGp/BdJpopiFlnfQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SVhXblpGZThTQzhVNTJC
            Z0s5ZGlBeXYxK2drbXNyNDBjY3Z5NStUaEJBCnhqL3ViRnA1UTdwN21sY3lOWUh1
            LzBCdGxjME1TRm90Um5oNWxqMVMxWWcKLS0tIEVVOWZBcGZJVEJEcmlOZUJDVWhz
            QzBxaEZJYVdqNDQ5MVR6NlcwcVU4VkkKL/aBmwUlx/wfw408me4C9HMcCKgjSgzf
            sdGvjiMpyoYaC8NLQup0/GGSHMwy5CvIoKpwlIzoGyUoejq1rI3Qdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T19:49:42Z"
    mac: ENC[AES256_GCM,data:HbTU2EZQdMCFwdaEBYaACMnbLGUYM4kY+vTqvAPSApl9s8ZoEq5VGw2TNLWVuODYyhtjUfTgkXmYgh4EIpbPxAy9zMCQOiS0c1PFBFmaDF1cX+DvSUwt437beV87x4hYqD0xseSC8mCbABJIAtdMPoBghvYcd5B26ZQQM4qq7ew=,iv:lif9hA7+9BOAsb1gbiY/6BmHGgOCdHJ91V8DGQfj/Kk=,tag:D8XaVAF/nUrqKAvOmE2ioQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
