apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: emqx-dashboard
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "EMQX"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "emqx"
    gethomepage.dev/description: "MQTT Broker"
    gethomepage.dev/href: "https://mqtt.cyphers.app"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mqtt.cyphers.app`)
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: authentik-auth
          namespace: authentik
      services:
        - name: mqtt-emqx
          namespace: mqtt
          port: 18083
  tls:
    secretName: production-cyphers-app-tls
