apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
    namespace: mealie
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:s1ePn5p+8T126wMBX3vd28VZvA==,iv:PbIRdDhZszX53gWTPyfjN1htaojpdLwUR1Ro4jje1EQ=,tag:fwJPQK70u3GEEzu1EFaQGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVURHbFBHV0ladjBLWmRB
            QnNRMG5HdU1YTDU0VDMyRzlaSWNPZCsrQkJRCkk5SHVTVGs2akgyMllucDBPZ1dH
            TEU1Q1NoZjFLQVJudkJsZ0RNK05BQ0kKLS0tIFdwQ3cwdUViVksvd2cyUE5GVUNa
            bVhtUmppd1lSSDl0ZW91VkkzdTVMRjAKGE2HYVhKveKNflrE1dzJV/xEj0DeyVI8
            eRmHkgXjqFv9ne+JeSHKRvm+sSzoA4me/uHwuDPYAc/HeR8/oCGA7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T06:53:34Z"
    mac: ENC[AES256_GCM,data:/yzEqFqxQ0f2bMfa/npVYVKBhhkv+5yD0xPHNhhpawmBP1QfAtiLAyl0JITom3B+WdAVu11tDviJpH442n/qJDGxBRI9wMlIHB1ppa88ybrFUePKElngfdYS9F1b9N73zOty4EsWgv9zugF2UFW5lFqPENk/hjmpcD0530VDJIw=,iv:tQnPZJ5i9eDKlXuEc9yW1H3uAYISAdRoC2WhmflBcTE=,tag:J1IlZzNXn0SKKkmY4V34LQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
