apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teslasync
helmCharts:
  - name: teslasync
    repo: oci://ghcr.io/ev-dev-labs/charts
    version: "0.31.0-rc.feature-premium-ui.13aae13"
    releaseName: teslasync
    namespace: teslasync
    valuesFile: values.yaml
generators:
  - ksops-generator.yaml
