apiVersion: v1
kind: Secret
metadata:
    name: teslasync
    namespace: teslasync
    annotations:
        kustomize.config.k8s.io/behavior: replace
type: Opaque
stringData:
    DATABASE_PASS: ENC[AES256_GCM,data:Ri66oBMBvecNiPklRg==,iv:7jEkRuIAy4zlVzMmrmjVn0/Xyo+TavDHHpspecRNboo=,tag:nFZDw+MXqFKQQYbuJ+aOLQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:ZwqaHztikH0a6YT6e9OL6gOORq4XE5WEr0IRIhu63TrdUKsPI/i0MDk/dbQ=,iv:K3aapv0/6ltuEZa24OBDYJievhCKVtRiEVh8XjCB0+Q=,tag:KZjheHFJEUh5OkD44r3WNA==,type:str]
    GAS_PRICE_API_KEY: ENC[AES256_GCM,data:bMaj8AKmRZ+PO8wQjdvO0AvXvIUHNli8BoN/JOH4mbLJmO6idFBApQ==,iv:JRy04Uc9yK0KXn/1YS+vzveznSJrNljzYM9v4nFoqV8=,tag:+11hzC+qxUcMtP4E/pf1Fg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:OWE55tDchwHmf9OYp73B7nhRBnJ3wAWMQo+DvOkhQQ==,iv:/qz8Pk64ma1Qyfoiy8slPDq/bDPA2gHyrynmCi/nB2k=,tag:uR9/AXV7s/jAF6IC32/SRw==,type:str]
    TESLA_CLIENT_ID: ENC[AES256_GCM,data:Xwz/J4VW5cMdZzPPHGmBj7ryLKflvDhDK3MfBw1jNN4zmezl,iv:nycdqAlJagE/wI0IB5MumThd8z7EImp5EjKGn8/I9Ds=,tag:M2ZQb/ntGcxsaKGHcTrQyw==,type:str]
    TESLA_CLIENT_SECRET: ENC[AES256_GCM,data:64L5OHyJ37Tpmax0P665s+gnRog1iW5p94w=,iv:lHKXv+dAmCpBtyNwI7Es9hiS54Hm7B2D2hrKo5jaa9c=,tag:MttZsbSGYyU5Z50rV88VCA==,type:str]
    AUTHENTIK_HMAC_KEY: ENC[AES256_GCM,data:5Fh0k2dS1o75eHr3AsWXxTUystMgzmLTuYxJVRm9SfecyC3qDszoIm+iCLnCs6f+YoFNcktBK8QLdSUa3V3iOJexUxftCWNP4CkHlFzf49Mntf5UFVr2nCSFOiHo2knVy+1TZjGIDrPCtm5FNojMRWGcIGq1FnFRnaZiuZ+zG94=,iv:G1kMzehLVp2/KVeDe/CrN3dZJIwlSBcylwHEVly8epQ=,tag:eeAo/LZIXJls676d+sN38g==,type:str]
    AZURE_MAPS_API_KEY: ENC[AES256_GCM,data:9Euxes0xXJeYJOkF0v7akRzouS8uoJQxUEwMUXY1NQYU2LEAf+Qv9nQV9y8pd23YXQi7PEEi1Wt67+G78IJwH9jg0r0lyFB6trV/pyHu6gZdtYkB,iv:u0b1LmY5O/f5WEr4grJJ3piRJLpx86Rx3JkH3g/K2Fw=,tag:hfeb4PJFc/AnmQB7Bhakiw==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:+Q5fOKK8Fyk2u/aMbTf6ZjZmsVqXqGxkfTFYoZVr2IUSh3HWShl1sjyjekDLgjLOmR8Lfx6NVPMqDAhwCqyCoEhhuBHx7dSOqkBo06RC1Gx1xa6iwWrYd2Mv+hzvosCXCfM3d7Ai,iv:eLFnW5jbEHlwcvBq9muT9o26qgg++jeMwaa9Xdsjyd0=,tag:mGvMOrIQkKjMyQxUML4J7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeFRxZTd0YzlCZFNtV1hp
            aWM4aTlrSzgvR0U4ZEhIMU1mWnBYMTd1K0hVCnl2MXI2N3N0TXAzcDd2Q2w3SGVi
            aWNpMG9WQWNMQ0dXVHFoVFpEeEtkZlkKLS0tIHR3SGJsSnRsbFgyZTl6K1N6WWdk
            SmtKY3ZUWHhMVEdHRUZpQ3l1VVVFS2cKi+Vd4f6+PtY95AcxjL3d0a/gbsqulpD6
            CU6OV2aa/izyiqwGIuCuYlFkIPqA51BqnWGwp7m9oZi6Wsjx4rXQ1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T19:49:39Z"
    mac: ENC[AES256_GCM,data:t7UQ9HrpIxs2ffpO32870is6J6mToT8zJ481MeJh7APbvWF9PsA5oVBI9yvkb1sk4C03q8h92Ouo7BTTsYnJa0IqQ+wwhdAKQUdOw4vv6Kr9i4RzJsKq/g0Ewdti1tOZglo7HP8NXbXMhYJNwTzVNtQCewhFoax3QGO5+NK2vO8=,iv:5/kmn3ZxFKTmNbg692zEPmpn/Bfla7JsUXVzd2PS96c=,tag:7B00gvyHkIJ6ys85MhtFFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
