apiVersion: v1
kind: Secret
metadata:
    name: teslasync
    namespace: teslasync
type: Opaque
stringData:
    DATABASE_PASS: ENC[AES256_GCM,data:QLmUhP/rteUR6gBDp/IfT82YScCnPpZl5lt8G6lB2lw=,iv:g+a8ev6p0M4+X7UeRyrVr1FmKCEQWCDQmNAYFUOLVoA=,tag:jvqQCjdjI/aj2IF8WrudRw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:4S4VoGMOCQ58oDmJ4nMwgVQFwIRKV/ngYwOMDAXQa2Bw+dBTLHqEK+xef7g=,iv:u3XQM3u/1EZjXnSEvlkUY9QeF7GQNZAuvsRUHVF5g/Q=,tag:b5G8PV6qOz+Hr1S5DOjpVQ==,type:str]
    GAS_PRICE_API_KEY: ENC[AES256_GCM,data:8nWQW4/eNKTB+pScnOya84tvGF5qiDz6r134JVkt+q6ZvQRjYN+6OA==,iv:jVNJz/llKpQJk/mhhVO4wRuhI2szz8tiY1teoCP1X4s=,tag:wZCI7Li5WG/WcnIbiZ2tpg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:3l8FPSjZrUswgMKcwdoispnNQxtkv9UnNSOqhxvFhg==,iv:AiOPlJbuxiglqQDL2Fjya/7erJaeS823r9a04TnBmZI=,tag:IzHIgQov9tu2qa5L+KwBuw==,type:str]
    TESLA_CLIENT_ID: ENC[AES256_GCM,data:Z3hZpMAp8aFyEhlS1qnkxh9I08kAXKRXc6kXPFlAa1m+prES,iv:zFagMEWMe+QE5zgvK2W7AY/L2VBU7Dp5SSHaec13W08=,tag:e1/llR/vI5KBet1jlVGFUw==,type:str]
    TESLA_CLIENT_SECRET: ENC[AES256_GCM,data:c+sxwCx6rV9MEurRNBk0wzYf/DXon9mTg4E=,iv:xAemwUQxFKsHCvHsdxdVYEuPhJuQ+Im2/zOksAFT3yY=,tag:yjZ5GbI2XuIyYMz7bpnFcQ==,type:str]
    AUTHENTIK_HMAC_KEY: ENC[AES256_GCM,data:BjtKBGJ9XdXYIRxsQEfoD43ERtpSCr5bnYcR/6+6EPZLhD2Mh3SKa8Yxlofs59R5GxO3p1lEDQs7h/aLMEYGNtXC1SiqcRN9a6HG7gH+uJG8jBROd/Fu3kfhR9H7KKBChByjopkvTOuToP/bJtHhLHMx5gqOjlBRAO6nK7C340E=,iv:FXpI2g1SHWo07ckwq5ATuGX2aS8N/SUsZDn/Vi4kXzg=,tag:Oup8rTuYIh4N+7KvqwR0GQ==,type:str]
    AZURE_MAPS_API_KEY: ENC[AES256_GCM,data:2qi7FOpnvcTt6qT+msi38QmMVVmo99e2l4jJkIT9NInclIC9tmAL43HuJ+gzt8Nmlr8sEyWtts5xsYADh6oF5lsBndHl1n3MU2ZVXlbnM48+WlRV,iv:PI++f7L7oVWjBPA8pJNo7mFOoCk+TyGNk7HrkIOBuMA=,tag:uhOvDe5wBx1+3C9zquE3aw==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:3uMk+ouyavedrpAxmrKSY4l0lhkKwTT4ZmcexxkryZiORYZ+F4iVclAQPFjCS6z3nkJWw6zZfcJqJCTVijHrYFYjr5+zpwJuiJ0MzfMNghc7mHDGvbbkyl9/Rp8nTfcUwcIxvR5D4cGAuA==,iv:XqDbjFCqMpmI9tcsViGaRoc4Gfg/UlASiGmdmtUtoX8=,tag:5aUbiFU6Wm+RgIBvXFXAgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd1YxM1Y3ZVV4WWtWeHBw
            SE5LYWdjZEtJam5CUE4xdWo0VC9raXVnNmdNCllEcEU1MEcyRVdpYkwvRVIrcVJF
            SlVzM2lGVVo0aVdLNjZ0YjFkOTNrMTQKLS0tIDBTcExsQlBFQlFvbmNOQnhJTkxa
            NkZ3YkFkeXlkdnkyZHhPR0ZXWmZVSkEKC8kwtSgsi6KX0BiPmaUtbFctVQus8lKf
            iiEqm4lEwodNdOFvyNKqAXhmOtrhtiwAQoh6T7h/ryaneSKBO+Idlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T05:44:04Z"
    mac: ENC[AES256_GCM,data:g5kWjSGcFEeWv9h8LwM9KdFBgAhSLqwEsKZjBRscMUWCXg4i4oFoHbXKgmr4H+5zSFzVgqQPxdTsyJYNwOxHpylDnW0ys7a22x/FDeSXrhR6Cc1OCENZ0N/UzSeS0aYetNezWCvuIGeHWNNUPYWYKbI+nSQea+dIrbjUPBaidOw=,iv:bk2X1gJ36FB8FQvfrS+5Vexe7R/uahJ2P9M9oBZN8m8=,tag:2XvSwt1vA37d+qdgbZb7Wg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
