apiVersion: v1
kind: Secret
metadata:
    name: teslasync
    namespace: teslasync
type: Opaque
stringData:
    DATABASE_PASS: ENC[AES256_GCM,data:87n5yu7qenLAeUEbeA==,iv:u9NyGCrq5Asfgds0HHyfeTRlDUMYiCyJFxyY/hzyZuc=,tag:3Pc+h7iEOso47vA66sJLYg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:TWH/+ptCoemtTObuHCOVfiCX04Zrmkfz9CKo+hgODI7uPDc4hVW5unS3Za0=,iv:A2bHNBxqC2bKlEJyRABCQy56u+XSPUZzornn2JvVhts=,tag:JlRCemxQec+RCVSf2RLHig==,type:str]
    GAS_PRICE_API_KEY: ENC[AES256_GCM,data:CVet0rika8sbtm+Gh0iUZlpBKATEbbcYwDGOh6ex8P+uoCTxbtbQAA==,iv:Vm1+RlsDC1s4Z0tZwG1VRRLe6v+zhPHQtcEbLSu2JfU=,tag:9dfa80YSmv/bsriEkjPdAQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:AHVjGhzljdh3jZioW+jkwDir27aLWavTOC1Z/LzQDA==,iv:8JHDAhL7kGZaP9QIBss8pM6qTjH7gIs39ZIhmTx2sCg=,tag:wH+Uh47IaOt7WhYrT3Xl5w==,type:str]
    TESLA_CLIENT_ID: ENC[AES256_GCM,data:vZ0JYTVtCaMSqcmTfAvEibvUveXkj8tnfZDdQ+XexWSdzXrg,iv:TU7q0O1vFu3XWUpsUgiS4xkQKYFG4U1fn+pOkxFvx+c=,tag:itj38TVRKGB378FtRtEolQ==,type:str]
    TESLA_CLIENT_SECRET: ENC[AES256_GCM,data:cJxAiToHAQUnVXV2RlOHriITrbQnqLNZcIM=,iv:LzCGiQeQdjyXLK1V7wG5B5tW9QdpFedWSM804/EShpc=,tag:Chl8XnxLxCTOtkNbCZV0bw==,type:str]
    AUTHENTIK_HMAC_KEY: ENC[AES256_GCM,data:B0gyb2Iicu/f8ITANmRzVG+FxK6jE64n1ka/8g3cJRpxwgUCR+njPl+x+PQOJJY04qTmsgo96ECSyckcnmVSr1V7WY73rimGYbmyUSK/wb80VSTDteOEQuF3LVJzdGL+3++wmY+/n+1p+4Bg7XG6jODsK8uImRc4xguDLtry8z0=,iv:amexXZT7Ez7Xnnph3q/y+ytu68Fjb3lnxOGg3sQ/KVo=,tag:foS79QwpuF/M6ok92Ri4IQ==,type:str]
    #ENC[AES256_GCM,data:HSTv0ByvqaF5AwO42J0BsM88R/V4E+omRsf1xc3iVteoHq4AiHgTgMZ5M5OQB2/5ObxNRdzqad77P9FxI8UKpRhh+oZY/dezEOiXYMysjPvZRV8f6wfLGWHs6a3ufZE0rIuYxQ1pxKIC,iv:Mmdvr0FTTNo5W8HNVMphYVVqDmi1678bjGCiA45c5SM=,tag:7l4fymUBHO1Mu0sgyzcZlg==,type:comment]
    MONGODB_URI: ENC[AES256_GCM,data:TjUcZALi68JSr55ciJmciinrz6AWqZtpANM0W75/NUAPWNpPqf1mNtyFoT+5sYpIOB1JNBmaeKxuWmmOWN/ZNoCYueK1pmbhd8bKKIRlZPShZRlwnir5Ci/qUHCw1+1/oETkXI7W,iv:0H32A0Lx8o4GXTTmS7mScveK3APUg06mIXEcJ/I+JUE=,tag:G7uU4D60WowXg6Ga99AP7w==,type:str]
    GOOGLE_MAPS_API_KEY: ENC[AES256_GCM,data:QvwClHrwm84cCVY3DNOBHX5670Gow6CxgYm/M+nZElmZm+7fkP6C,iv:T/JEESdL1vqN+Pd49UAwwZJ9HC9mBH/qwCcBC5GRcv0=,tag:oJ6pZrhm2v+51fvTwVyZvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYkRhZWgwZDVJd2tUVjkx
            U0E1dXE1eEtsSjRkbE5CYmFMeXVabHlGNDJZCkhDWXI5by81SW13dlhPSEJ6WW1Q
            ZjFYeDBXMUJnQzcrTGlkazU1WEZkWncKLS0tIDUrT2NwSWV1QVNaUDBDVktJVzM2
            VkpDWUl6NWRiUnFNWEk2MEVMSjB3OWsKxSdmRmtHrd5ENFnWvTavH0RJG2zJi7fB
            a4LaVV3YvbY4gCPCBQDsuuHycBjUSKqlTtWFohgtJ74eedz9SvjI/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T23:07:09Z"
    mac: ENC[AES256_GCM,data:D84Mmbz3rC62+DdpdgRT9KSHrhHrxSl/rnHffGk5EzGyOakqhMvumcU8svu9jOVa8mHP1j9OV2Y4AG65payfsC0hwvSBiS1Q/qhRKPTzzMxg0svEhwRXTwvpQIlL0NOmXIkM+hibuSD8+38yz+PPLK8erXsMKPFfKW8DwPaqZsE=,iv:dyh6UzRmx0kO+qWx6yddI4UlK+yKzgojHyojmfmgi6Q=,tag:IuJ1VLF4A95iBKgPWaOAWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
