apiVersion: v1
kind: Secret
metadata:
    name: postgres-v17-postgresql
    namespace: postgres-v17
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:tZeHuTr2FXIUi6kXxciWxfnbfDKZR26wpCIFLzVh4A==,iv:rr/kxC+f6MPWt1OWi6ZnWVT6Gd5/lxy97kB3/9tptj0=,tag:eKRKHLikIzmx2V9t36eD7w==,type:str]
    postgres-password: ENC[AES256_GCM,data:nuaCZugJRtN9flV6kCM79vKW8+kMopQO1SXBo0NUng==,iv:woAXDCWm/5XxQOPLEQMWEyM+Eqags/HrP4kNeL0pIhI=,tag:SxsN5WcOKGvp0ftbvefrnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcmloT0xhVklXNXFwNU5R
            amtqelhBYlh3aWpXM1E0Q3lkYjRJcVlGQTI4CklZZTFjWkNaaXo4V24zQUJuOVM5
            NWt1K2JxWlN3NHZDN3BSY2ZVQzFqNk0KLS0tIFUvbmQ0T1NUOHd6alRpUXIwWHhX
            TVNta3ZjWmhFQUdJbis4b28vMlRWMkkK1AaxTJhsbJUk/3a2j5EA22KoEiyRwoYS
            dvhUuyfXtQGIf4YMPNJFxp11op2Sb66MctLSx5+MdXP6JGt+VgiqRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-20T23:20:55Z"
    mac: ENC[AES256_GCM,data:8aHyOZwMlJCwC4aNHqk0GlEmsBvJ8LIAzQg5ReuDvE3xQh5rKDdaL6XqKEMgNHNRzqQ4v0MayklkpKrbtR4DiW3S8ro96CmeAlqGMcL2tOonHgA40opJVT6TFnhtniXs1ST2ZgkA5XJsQkVW4E3WAuXeC3yLtRCKeoa9WG10pAE=,iv:A7cAOkGblWRMfnglHhKK5qnUo/hpWXZtIYn/eskG2AE=,tag:puE1usev4j4fsvOQpmUUaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
