apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-credentials
    namespace: nextcloud
type: Opaque
stringData:
    nextcloud-username: ENC[AES256_GCM,data:zOt9dIU=,iv:+/7ZaOij4eoVgSHFLrDQr0R/DFnuvEJhj92iC78/y7o=,tag:qHZE2Ef5OEUKkiTs31CgmQ==,type:str]
    nextcloud-password: ENC[AES256_GCM,data:LEoTRAEZiPY=,iv:VsStQhicejQaa37x9M0AqJ+Rm8Hov0JCaIwbZz+wYgY=,tag:Bs/fhD6nW0MaEd+Pwch6kg==,type:str]
    db-password: ENC[AES256_GCM,data:8CoCzN3SxHpY37aOfpBNNJNA5sCB4BPE24cAeIwf38SFos6pnGfZ5XB5tv6ayg==,iv:lNa9/j+diDThSvNNX9eAWNam1xdwFAIpCi3ZZDF8WcM=,tag:M9JD0RnSneYBaoGybLx98Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQmxwa0FRODFrTm1qalRQ
            YTRXZWNCMzBvL3pGRDlWT0o3L2V1MkZOTENnCmFkaWVibFRPamhWbnFuL1V6MUZh
            Z2xuZEFXcEZ2Y0ozZ3ZRSW13TjVna2sKLS0tIElOamNIZ2FOaGg4RWF1d0VNcXZB
            UStacVF1QTRjWHFybkVqdXVzNEFpZTgKRnJ9/AlolO5Fv/Mz6FyA6JG01WWdq2DP
            JFJhw6f+gIZ/YXkPJyxXsKa/EMaLwcuo1gDiAHb+nRRGIvkktKcUDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:52:46Z"
    mac: ENC[AES256_GCM,data:8N0agEYLhsp3J86ThVdqB9eG0U/TpqMI3eaBkUQDIoyBhMo0vCFAPbC0TXtmPRX+F7pQ5W5n+sFFHiFelyTEyAUnntGlB3rKOXWvjAaKAN/hO2UgWV05IC7mMqhV+rfdGJXyh7AxBMQM9waYyHGn+H7qr/3aupkhtxxiyvH3U0M=,iv:/2xuyH0P2qDsEYmtxCw+iM98IqEQKygcP++dkmn51Lc=,tag:Ab/2XBhm4cz9leUBHrHXjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
