apiVersion: v1
kind: ConfigMap
metadata:
  name: timescaledb-config
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: timescaledb
data:
  init.sql: |
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE EXTENSION IF NOT EXISTS vector;
