apiVersion: v1
kind: Service
metadata:
  name: timescaledb-headless
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: timescaledb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: timescaledb
