apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: timescaledb
generators:
  - ksops-generator.yaml
resources:
  - statefulset.yaml
  - service.yaml
  - headless-service.yaml
  - configmap.yaml
  - servicemonitor.yaml
