apiVersion: v1
kind: Secret
metadata:
    name: timescaledb-secret
    namespace: timescaledb
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:naHyt+EpTRQ/lIEFrtmoHNTNHy/q1/PMT8otDFM/EMfu,iv:Q6PIlDPOLJ4EagVIz8ifJQJOQLMF144XdYknBC9gSM4=,tag:tS8FMULj8oQXBxxL2YPQEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWHEycmpRTjZYSmEvME9U
            S1RXK016M2U0RjhHOU9tWjFaME9XT3pKOXdrCll2NllVOGMvb1FTSjdmR2gzSHdy
            b21uQzNFbHh0WVg4Vzk4NVFSUjJGa1UKLS0tIFdNYzdHMHhsQXlRaDhPcStjZksv
            MjMzZkNURGhvRjBkMktLaDNsYWZ0U2sKP4vv+K/p0ciea5RmS8kcPQAQI4FvYRnL
            aAPLBpvgKRupZIxbCLu1fUxj89kriLSzCP6Aw8pR9dcZkNL4SSLwqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T18:00:17Z"
    mac: ENC[AES256_GCM,data:CKyhP4cr5L9mUUkRPMB2HrqQ4AJiI+nTVjwhWJM9c0usbK7ltoVXGnFBOmYdQ9S5iXyqxoCDaRuuBMMOqzPYac6uvSLNSPKLH9F8hAmyU8Wt4UenzEXAMXbQnJwaYrkYcjsaAjMeZP62NjMU3kbYlFC5FZH9PF/oZnrnPnJeVlo=,iv:tPof1z2BS4o8CdyYBNIqJPgXroAiOqa9aQ3moysA1WA=,tag:khHS4ILfVFXbdhitrUzT9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
