apiVersion: v1
kind: Secret
metadata:
    name: timescaledb-secret
    namespace: timescaledb
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:S1uXYPmJwQOnA6GX2YkXYEZ8EsrBl0iKqHmbFHBGBIk=,iv:YCSkL2hhJLtcVjLREGnMJ2K21lZ7K7bxrCRzQBjV08k=,tag:r5Y1IHjSjOHMUCkWZ3Lr2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q0FLU2g1SEtURjkzRUkz
            cHFOemc4eFpEdTVNL29XcHd2d1VDQXNidzJrCmpEOFRmei95QlNrNjEyZFMwcGtX
            YjlNd1l0M1BlMlk0NGtZMXJHYXdBZFUKLS0tIFlFNHlqUUdlSGFFTFdFVXQ0Z2p0
            dmwvZHRrUUp6Q0RvT1MwK1ZpZkk2Nk0KqU8wx8H23o1oK062CxvxWPWguv903kVj
            5vp+CKpEMXRz5oeLDWNzVP/WG1uxM9feuVReI0I5FrrNffeN9aAUUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T00:00:12Z"
    mac: ENC[AES256_GCM,data:yOPgIUP61SAxSvWxIuO6/lRXJ1Om+jBcAt2ouRYLSe/kdM6R3g8MHjJ1yKsA43JMqYEofrMpd9ZLdbA0KkY+hzBJcQv9JDmAoUFdiP+IeMYEda4qxmqJwv57468B+Rr5ee4uKJmsSwMHHdczRhxvCDCGqOr2aWeILC6HjUW+uB4=,iv:FWE2XoAR+fvKNFtJnfNXGmqDi8rY6GwidJUEt9/dquQ=,tag:Pf/5r27SxtiIIjxllW/UAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
