apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  labels:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: timescaledb
  annotations:
    metallb.universe.tf/address-pool: reserved-ip-pool
    metallb.universe.tf/loadBalancerIPs: "192.168.68.210"
spec:
  type: LoadBalancer
  loadBalancerIP: "192.168.68.210"
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/name: timescaledb
    app.kubernetes.io/instance: timescaledb
