apiVersion: v1
kind: Secret
metadata:
    name: mongodb-exporter-uri
    namespace: mongodb
type: Opaque
stringData:
    mongodb-uri: ENC[AES256_GCM,data:WOwgOArL4Hjhsm7HRHh87vPnA8qwbRbixjXPwGno0FfwWf/2Igt8gum3498wUNM5sMt2WQs80GTd92l67jZHMg5BjGgxB2fcNhLVd2MLeLav6KYmg0ba,iv:FE3rQM6bzfrnlro6oP+QXOnNI4ifEHdLDnrR9ZvKBXo=,tag:joiB+wIP721D+IJpPukgsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZczNFMW9SVEx2MTNsS1ZT
            SEJkOGxTcEViT3JCK2xlU3RMOG8xelJmendvCkpuekZXbkR5aE1YMjMzVkFLT2lV
            aWNqUXRTWCtyWHR6NFJjMmFTSVBDWmMKLS0tIGwwRnZ5b3NZa1F5WkdLVzhMbUtZ
            SEZ4UVpYZFExVnBjZUNQN0ZxSXV0c1kKz4exTVxRIs4vZU40xlYXR6NOtCnLAS0I
            /OFvJFxC5l+0DT+ai7eNzIYlPOSW012MULtAPYZvBbMhKpg7BNRv0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T21:48:20Z"
    mac: ENC[AES256_GCM,data:HrJCaTrD8xOmRfYBE6v367/6AQig0ZuDMiGpgtgZzDN8SGuEWsOIkOQ70v12NmCJyWo/l3BiFh+EXKDGk1e/IuVqk1ohABKa9W7Vz5a2vVUmsWZwJkGhzMwXhpcYSADCXRPrvhImR4g+bJWajST6/413GzWaHn3Xr3PObRDdYFo=,iv:VUp1Zdwe/aTkB9P6i+O+Vw7oImlyx/BfP62lKQUBOWA=,tag:1IjC8Sl3SOrs0uCntZ/c1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
