apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: headlamp
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:QMWnrBEvIqJ/it9cRd5stC7DYymMcHHMOeclcOSjUnvo0sXCJtlrIA==,iv:ATcVpaAeZDNCDXP/86KxypT2uwOtubrIS8gpdOv61qA=,tag:GpZkM+pY9FdJ1tof0o+3MA==,type:str]
    clientSecret: ENC[AES256_GCM,data:lHb2sPGJ66YEg1pkjv+XtfV9Xev9qme5Xbeia/ZrPBhrfxQSs3qOPNEH03Cq+T9651fUtGm1zR/1Bvz9dtMmAmXuq7kDruptl+UocFYf7soSLiv6gY1tS/FHry/vEn8wvqmKgHAFN9VxYb8UMVVad6jw9JjJa3Qx6pjH5UphtE4=,iv:qkluJcR0NUb+yJvzJDStotKadV1sQe6HA6QxbGpVaLA=,tag:eEZlqwvB/vivTHy4/TofiQ==,type:str]
    issuerURL: ENC[AES256_GCM,data:so1hCoAZQ0huuPCVk/NaWHc0yYRpfHD36AyI43usd1wSXR2pL8Fbpnd2OZEf4ecXoxyJW+Y=,iv:gLxzwV54QGhX+FYrmBmTFIjM+N2ZbLImSiSdLPOEZX8=,tag:srxWmppJjOhCmkOf48nQBw==,type:str]
    scopes: ENC[AES256_GCM,data:MwGBaagJKhpZPSFVlPKjHuazxaM=,iv:HoMFk9+1qoBCAkPFwe6q22K1XEmuqnUdP1DkUHbHbGo=,tag:8wEAPU7cWrrkjnFE8P40Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISU1rbWNGNWhXanVEeCtP
            d3F0SU1lb3pJSS8rYVVWYXNBbGI3RXNkY1c0Ck9zcU9wWUE4RGt3R3IraVozUkV4
            RTBMcjZjYVpxUmhYcWVpRldxK1J2dE0KLS0tICtKUkh6eXIzb2xROVVSQ3NnN3B2
            cEhzTnZmWmFWMHQ0a2tMeDRHdzF4Z3cKDD6Cf95bHvx6tOfQGV+ru3t20jxePWz3
            3N5EO9IB79DzeXgmgeJwCE0fDinhCjyIJpAk17z8uSqEhmrR+tF1iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:56:04Z"
    mac: ENC[AES256_GCM,data:rBoOH/ilQ5gAxOzydsxnhodHTsFgYXPIVNAcl8KRcRpsyOZdjBWEJRePcL+iw7wbO3YPGkpavz8K8Afw7QG0hRd7v/QFU4KaTW6Sj5iXsz3/QLjB1UgNOiAtnDivFVAP5/Xvhbneoko2L//Deveckz9I36AMlAvfsGSxjDqiLnM=,iv:BOpr4u65f5T9TuMl6EcSlp+IOBe7CbNG4l+jLV+mJO0=,tag:qMjCseSlXlzZDPYroZmsig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
