apiVersion: v1
kind: Secret
metadata:
    name: oidc
    namespace: headlamp
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:xECWw2JsttcjFBo3NG7XB1vI1l58GGPCpQMxBmgYVvQmWrQfX9yk8Q==,iv:fSfxWsBMUmvGJ5kW55ek23zS/2P3r9Ba1JTQ7FMJ5F4=,tag:DhzhfjyvdmRr9pBfndGWUw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:TcAfsG40AqZzx2YcCYFgBEWaUn9l1gOsb426EwKel6B+5DMQmNfHv5MVn9QR7xw0Sp/NDaBVURa6qaxnx1BL4D1PsyohK0Ls/7Z7Ozpa7A7vw1IiniH4OAKFtn+b7OcAeKV11AHmxTtibNBNKe+wP4JrxOrTJC2f4Ho/XpGSgtg=,iv:RY6y3gOvYtpYG7iqFg10jk0+21vPp0nvxYQJd8AvDFA=,tag:OOq8tHOtpMdo/qaEysFRlw==,type:str]
    OIDC_ISSUER_URL: ENC[AES256_GCM,data:lnVzlKhwS8vqw/+Ip7FkkGwZCEhgLqP2r18Dmv6blx/BT+p7nDzsSGwvTLjYDrltTCY4MKo=,iv:W5yDZdDyq8lGXDWR5zRkT1Se/5sXq/gpHVNAtKIMcK4=,tag:dv1O2UXIbvjlXcPqyJkQWg==,type:str]
    OIDC_SCOPES: ENC[AES256_GCM,data:D10/3JKr7p6mUpuIdqzKrLEeCAPdPMFotDw6V7FyUNqtQds=,iv:vasLmFyaaPUjO8U+lXEPY+wWKhBSqNPsIQ43CWbrMRM=,tag:MQNuV8MI/DsVSZrGkCOZjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZk5HNEQ0WE9nbUNmdnRD
            N0VTUXhnU3hVL01yT0l2djl5WTgzK2JVelFBCmwxeXRXQTkwNnM1Snc1bU9xRGF4
            Vkd6Z0FTeVQzcjRIb29LdWIvWGtNcDgKLS0tIDdPcG42b2VRbS93T01vWXArelk0
            UHB0bW5DMDVxMS9KMzZnUU1jekVEUUUK7P07lTdCeJLQE94WlywiKyHTkMYDD/5g
            YCo5vCH4BmtO18sSdK9iV3nhmMIb3PMW0z5Hk6wYL775SI0GFNEBOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T04:17:35Z"
    mac: ENC[AES256_GCM,data:Ld4Mn7h8fS5T+pqRWyoXEtWuq3QVb10fdrEX0bnnKXy5YIm/950hRXpfkeTSPXEq/TV0dfifLlcDvQM8A6fonsSJjoaI67dBCY4mXOODA5RmM6xgstfQZoIuUVHPFkc+3ZsZCpoxayDVfnEFZj7nh1La970l01FyvJvaf7hMuhA=,iv:58cPi7FdjN8g33eKqapv4fndAFKDJOhJ8nyRQToCTFc=,tag:U4BUEfXoYCQsswUIZbKnnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
