apiVersion: v1
kind: Secret
metadata:
    name: headlamp-oidc
    namespace: headlamp
type: Opaque
stringData:
    clientID: ENC[AES256_GCM,data:aHwt+EyYzLjCUwEhIs3KArnjud8Ihdsw6s4Za2mvrOl94Ph8Qxlx3A==,iv:wNQxQo9W5f9WbHPpt1iuBJZaiWvn1QLcS1o9Ke1KthQ=,tag:21+GbDyITlMlN82TOSomDA==,type:str]
    clientSecret: ENC[AES256_GCM,data:I6XPfrmJ82FOIsKLGIUeaimxhP2kQ4385Fb8VOWnak6UupwyNdVLliGfMIRqIDkCO76QoBZtq+wdaHw9nnSZ5dyOk2+PtH9G5I+4jbkY+Qt5Uf9aaROwSH9oDeg16lY1FjzAzszrk4kzMMgx+tbdo4SBuOcGSS8jDWNeBVV8Pf8=,iv:Rvxa6LOgsIsOK1xobAUElM3zAvtOcleT/FSVjiDZyQw=,tag:YbQIc6GmJ8PqoLhy52i/5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNldIMElLWk9QMG9wTFdV
            cG1vakJaaVRyMUl1SXZUQ1B3NjdkRWsvUUZNCm9NSVlLek5Fd2x4TEcrdWtubUJQ
            aFBiRllSSmNLWUpKYXRXQmI1QUZ4TkUKLS0tIHlVNG1DWUxIS2VsL1ZqQ1k5Wkc4
            a3FUOGdnNU9pV2s5RTVCemVLaEhYR3MK72U5r320ATP1kIlulDt1m66JhmZlJHvs
            KYUXztcYG5fAUr/g9tEMZ+WjB+kOeHbg5CqCp6Fg+tj1DPzSQqFG5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:50:15Z"
    mac: ENC[AES256_GCM,data:sbnnkSg7S9+aMXSRInRn/mIcjsZhm0tCCBrK9rknEYToFCmHqSpW6IAQmMMpKF+1S2MZjP10CEgEBegsxJJx5mO7opht6MmFnLiuXgrl1tSp0iJlfaLpjWrMmmFOxtnge1yBzIBAuMk34+UcXSHMfDZ8xH6mon8h7b51Of+KMSI=,iv:eFFIuNdXuCwz8k2AOMeJglUYIrnhkByPxgPPzQ1gdqY=,tag:S9gTGPBXmwAnic4emjWVRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
