---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/atulmgupta/-k3s-gitops.git
    targetRevision: main
    path: apps/adguard/resources
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
