apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secrets
    namespace: openclaw
type: Opaque
stringData:
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:Ix7fAdU0M99eXPlbNhp8sn9hLVQUFY8DfJjSrCn+eecwg/3k/vMCJsMtU+KAttS/nWykvy6jlpnEARTieyI3GQ==,iv:lPd3JhwdqXOHzTmi5dEjKvbY6XevqAfJ9j1tDnnb/os=,tag:pNElMHJiGyund/NCGMA3Bw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RWFFWnNLTWVOMURkUllN
            RmVCeTFIZXU2Mm16cVp5djJrRWdObzJld0U0CjJRYTdjemRJSFpzZTJNUjhwSkFo
            eGpDeDlVN3JFelJ0a25UT1NmaE1GcVUKLS0tIEZmaHlWeklSbmdHd09ram9NejlN
            dUtubUp2d00wSlhOTXNaakZlMmlnbTQK84XtP//K8xODGWi80U+A8ZOaNyJGj26q
            3NRU42yleABcDsxW0hJEZT4mbF22huWHLGKYWmzxdHEk8OfaKy3wdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T21:28:31Z"
    mac: ENC[AES256_GCM,data:KT+tX1I7tY0cazY+vZq969W69RbS6okfyM436VaDMN8RC+/E9Uctx7CBSV2uEQdL5g0gaPMRhjquZycdhJpNggxuLWA9Al4L9f2l2jqxqHB6PmFHJk/ICXrM4/JUWGWmvl94mPvLk5IEXIVY70BS2IfiXofr6hEDmtfaJpmo4n4=,iv:Z0811pFfAWnExndyxiEEt1qkXf9gLamrI9+xJ8Vosac=,tag:KB0DqOkDvtkUR5i5KtUliw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
