apiVersion: v1
kind: Secret
metadata:
    name: mariadb-credentials
    namespace: mariadb
type: Opaque
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:pYqBWCke8lEEx4l5NLjpf9OUxzcdG4Z0QvCkwQWlUT4=,iv:nCJ388t5EysrjjYz0ZvU/sU26q3cj06aUu1Ab6cCp24=,tag:/8nJauBAEzWVULZ+6sIQVg==,type:str]
    mariadb-password: ENC[AES256_GCM,data:CG8maP7NXj5x7ZVVZ0z6Yz9xTPJeJpMvjo9IWebRD/uC,iv:OwI+muQ5PI1F5cfjXpiGnuoqg6WMzsJYrEVFr0tqnC8=,tag:wdVzmQfcrANtEH6oET7FZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM2FEV05XenhKbTY2TzNP
            aTdveFQ4SjZMMkpDVllGNWNsQU91ZDcwbnpVCnRZUXFscmtQaEdRQTQxdThMRUpu
            ZHF6bXNDZnJZNHd0cGN3UHZ5MnVoUTgKLS0tIFl5ZnYrem1DWFl3blJQVTdjOStX
            L2E2bE5ISTVxSUNTOEtLUlBkQnQ1VkkK1WcnXLKaxpgm8ys+stjgBnHAAPwKt45I
            5FAj9lajWSBlPfWpjHsCX4HybgZlikVtzeoo9VR4yM9Bzl3RkeGmgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T01:08:58Z"
    mac: ENC[AES256_GCM,data:hp1mBAl9tNW2xuOfr8Y+IM+pvaYwS1dBi35BKAoFJI3bRjxsPLzaZu66/6lL0Qjy4wIn6UctPN2iKYBzsJaUgulN+HkNjUQWWksE8nj5PVhMFIUFNIabV6EzvMN+EZ9D2/QtFCJfKoSG7FXzqdvtmecRq8LNqHwsXBqvlnR6QL4=,iv:m1xb/PsO3b3JhOPAPobbOqRU4LsW5l9KjoBRh6GEKuQ=,tag:hYCyhgV2LDn9d3akxC0PjA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
