---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-resources
  namespace: argocd
  labels:
    tier: infra
spec:
  project: default
  source:
    repoURL: https://github.com/atulmgupta/-k3s-gitops.git
    targetRevision: main
    path: apps/arc-runner/resources
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
