apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data
  labels:
    app.kubernetes.io/name: navidrome
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
  labels:
    app.kubernetes.io/name: navidrome
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
