apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:OMiePRY=,iv:qqL+Ai2LXuh6Lw+FUZxxoqYKFZoAidpIjdyud5WgHVE=,tag:v1T5iJUDOmnk+xoQc7d4Bw==,type:str]
    password: ENC[AES256_GCM,data:leGleXxxsZ0KavzCm0rs,iv:1dmV1HNkAM2ft/vGctDPdufUFbYnlBX59JK2YsdWI1Q=,tag:UVf3CrHR8whfdxSf1Dg/Bg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOG44RUtqN1BLTHZhTTJK
            aEZRK1krbTlrbVZjeFZzZXdSUkx4R3E1Tlg0CnQ5TkZPOWlmM0IwQS9qK01XOVJP
            Q1F2Rm1XalArRTg2amdzWEZFK3FFdzAKLS0tIE1BMHQ3Qkx3Rmg5YTIzN2JpTksw
            OG9HdHFaZFAvU1FvT0g0MFkyeWJiUWMK8wB44PMsOpaahYpG6SJ7aNYFfueVpxi0
            fSQWgxImNIhHzwEZKoYUaWQrXNJwdF3rEtZuGLnju5QTb3ejbmjzYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T17:02:37Z"
    mac: ENC[AES256_GCM,data:Gz28HmQHt1U3aKsPzDvSQD+IGF9RqQk4ie7zpouE2NSO7wjHzGfWeyc4fiw4TaUt1MF5MQhzttkB5dTmKUjdVZo2Rfrnrg51W9pAcT2PRwJ/heL6/ojv42c90HvXRAnA+sQQQuy80NdxZ1y7S5YKAIqS3fqijC+O2+j0DDPsq3k=,iv:4NiZsu9eB54F+ugZiv0kKq7s2//nsRJnPQSCbkMgFlM=,tag:39g5HB55PH/RmqJRuniWtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
