apiVersion: v1
kind: Secret
metadata:
    name: grafana-datasource-teslasync
    namespace: grafana
    labels:
        grafana_datasource: "1"
type: Opaque
stringData:
    teslasync-postgresql.yaml: ENC[AES256_GCM,data:lnKYEw0xq7v8y7jZYad57NZy4pih3NO/E4g3IBL5EJhC5GZFLwFXn8Vuvw2qyhtWhrDnQTk6k+iDtunwXWZaOMG+S0AhXJaRYBlFe+H4eDxX4NJMIU6dNa9sWt/bo3Iwo8pNAIIRHZ2qt6l7C7KVlbtLBeuyfx+zF59deLzcw5IaUD4qv/7jNRHsn8aW+w9fT4a1tjIzj1QUyiudq2EEUmFg8JdtdTreYoZmFCnIP2dERLM0/FzdyTYM7k4oD+W7+oqu23Z++CA+wJwovYYn+IsbdX8IYBNUI5qHAn5Y93mVNVE0vDr2Pma9e3YiTLiZj7tRGGT8a/n+ljkEg9xYJ8hvtu8BYKhhVEhvPMZLLVUfB/76Tdkdt9iqCW2nQBD4dTuRVUyHQQCkOmo6obH7tQysmddwY/SuQv7zr+s2jh2oembiUJwutHn3flPYg7NUZop4VurAh4+F4bqih8uJteer2q625bqIK+K70ofd/J5XxANysH9V5Ox2wukZeq4YxUkVRbS6ut6OrAP7JBpMpZX3kmWiNVeXQEj004QlsZsexY87wBROCCwQo0EGIywWnn00uf+yAwkqHll/05WkET0KBKSnXehDWwgSzifIiI4NrngFlhbe3e6GxMjVEoEoN1SpNivqL3EQ7Ydl1EbfSmVLb6LCsYlDGslZp3l9MDsopU61WATWDmA/5A==,iv:5HbHZnMHBkiO6Ejw1hMTtRRpEU5uEtRq8Ze4vGc/O58=,tag:S1LltHhJl5E4zu8RIFWpZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0t0LzNYWU5TSU9MSW5j
            QWFLRFFnbW9VR2x6YWFnc1kwL1lwWGtUb1VjClRuTUhXRzJlb1RnOWlTbVd6Lzls
            ZlUzem52dlZrWU5FNnpKWHY4UFZ1dmMKLS0tIGtUVFhqRXV1aXAvZHhnUmJKdXd2
            NTFpN0dZU0FtL2ZXaGhYaVJMMzZUd0UKjgSFXLq7rTfrgIl+x4916r0N0On6ZavE
            G1rNVeRdzd/uopEz+wJle2/rCBqBRfaThYd0C46Xu18PZ6r1Us/2hA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T22:25:14Z"
    mac: ENC[AES256_GCM,data:KGd5sJCsCb6EiyVelLoFMUDzP1UEQHEI3Zz0Tv0DdhNtiCjIAxa2MuOc7raSNOGpIGj1EMyqZSgusFgA/3lhnwMUdB0GR2Lxy3MtX1BaBHOoaDgBYsZhgnO4VSzqODoBTjwSZjOSEUR5xTfSpBLMlWbl5hc+TvgEP692/Rho2Hc=,iv:qG8IljqyaXvkJZjmxobswHaQNgZCTacsoyBA2HfCNTA=,tag:uy0z/F6V1TPw2/qj6a043Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
