apiVersion: v1
kind: Secret
metadata:
    name: grafana-smtp
    namespace: grafana
type: Opaque
stringData:
    user: ENC[AES256_GCM,data:XPsP848J,iv:qqBKpNYrXaXyoltUIMaDJYoBdrEbKyPgYuoaitSmO9g=,tag:nITL3fiThW94i1Jtws63ZQ==,type:str]
    password: ENC[AES256_GCM,data:/30G37j0AYie05NrsptokbCU67F47E1QYJ55GV9kVybUkoqGtbvZnICOTUpmfq7zfWqfMQKG1h7mPQKRWiEntoqd0MR/,iv:295bulpryw7UrfuVfaq6XZh/qz9Nmnevy5iaNEDy7ok=,tag:DS2QezNs0Bi5CXbKS+Gbbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUzBPbGtsSVdGYWFiaUNT
            cW9weDRvTkNyTHNQSFd5ajdHODA1ZFAxWUJvCjBhb3pKRndLTUFjN2pNYW1nMjhG
            THlTbHJtU1ZONXVCdUs3VEhKR0NhRk0KLS0tIE5iVWx0ckltN1gwOUZES3pKTTZR
            ZnB2OUdPbkY2VkFlTmlnU3BGZmdYckkKbxKcR+mBcFSQXRC/WJEG7aZAnGygdxAo
            QvmGGy3pIAeRHfZQy6YtCvB+8wqSF1FebY6Rbn6mq9ptpkdBDGl4KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T16:28:15Z"
    mac: ENC[AES256_GCM,data:xnFJ2V5un+m/vA3vMOslan/J+pIvzvmO6h7l+mD49UHBL/CfIaVJq/wWMQukiAERGEjcYyff1mQ5SbJojEfYLwkmCPVF3Imcu3akn65blQpS1rR4lZ5b4Tj4Q/RmGZlKl429E9FBAP/nw6Ao2CTmG4DV0oRKfeWh8eqeCoAogoA=,iv:mM5+l3vlc05plxby2y4L3K9oH+LQiwDmQpNyHpjeV3Q=,tag:Ytvbds2f3+MwRSX48tC0cw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
