apiVersion: apps/v1
kind: Deployment
metadata:
  name: error-pages-custom-error-pages
  labels:
    app.kubernetes.io/name: custom-error-pages
    app.kubernetes.io/instance: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: custom-error-pages
      app.kubernetes.io/instance: error-pages
  template:
    metadata:
      labels:
        app.kubernetes.io/name: custom-error-pages
        app.kubernetes.io/instance: error-pages
    spec:
      containers:
        - name: error-pages
          image: tarampampam/error-pages:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
