apiVersion: v1
kind: Secret
metadata:
    name: vitasync-secrets
    namespace: vitasync
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:4zo0p/e2wMs2nd/g275Sp9d93wOvgyw5g/YQo+a64nNiHKHxEO5NnW2TlNizCrfQxW/zzbW2Qd44TIS9JqlWNQ==,iv:wArNLyxtzIFanDzhPrGVL2n6YR+09CF5184YKLhGJT0=,tag:TT50GJckKug8QrcP1uddLw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:MGskz5S62GkGG1VHRw+OZjhfTS3mQ3zpIKmY63bS4tGDZKN6cpcciq6HHckv/EpzJdbfxAqtlEVEcQpfRjGvmw==,iv:0K8jonSE/kYMSSsO5FPtouP+8dx1A4HFChgYuhqR2lA=,tag:Ll41G8unsKcgNeTrJyphFw==,type:str]
    ADMIN_API_KEY: ENC[AES256_GCM,data:w1gz/3JbIzPuFA+WxC3shZ7nz7C11Gc+Stnhe4mWrppUftndJgBohUT17tYCpPfp,iv:lJWqu7GwBvvuapOn9fUrgIqNC+2drZjr9OmSmybq1bg=,tag:faLym9nS/sES6v90fd+V0w==,type:str]
    NEXT_PUBLIC_DEFAULT_API_KEY: ENC[AES256_GCM,data:0ryZCB59R1b0plAYlQD5gZTn3qyXBnhjB1CJeInj7IQAUNrabJhXBQ==,iv:AGrS5n2Ti0bI+r9ir1fMmzj5OuQn/zbrD967NLlRB1s=,tag:K+Vu1hlkPBfBY3BOupvucQ==,type:str]
    WHOOP_CLIENT_ID: ENC[AES256_GCM,data:ZdspnEIuaYlBYg13l10DcmeKDzUfrY4pGWdVkucsq9MHzq62,iv:NBdkRzVLuV4wd8MJRrVCt60NT+NsBKVqRTaRnZ1THLY=,tag:BwTFHu041dCiQGTGKFf89g==,type:str]
    WHOOP_CLIENT_SECRET: ENC[AES256_GCM,data:QP+qadoa+0Xs8WvfAvdWAwn0uKIfk42wcqiYsPyv4R0wX4HMYjU3HaZImFBE7N1D5E1Hi1hN0ngtUl47br25Wg==,iv:8CSiKkRlUQ86i1QMRzm39m5LGPbq8BOm0Wmv2KJoYj4=,tag:7Nfh2pnVl9zdQtN3b2CfiA==,type:str]
    WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:1m+swj06/D5BCvDrbvXup4fuDYY/gqg0N1luaeQfwifpGPWEZ+zzt2pTuYrtrqDPSd+1DKEBseGGWphpQk1Z5A==,iv:Yp6RrSNE7FZe1p5C70gp3RrPFutUUxFbf5wcVElB/6Q=,tag:heYMLzaOYafK2GLtLudHqw==,type:str]
    WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:rS3t67MESh5i3W/j7di2J5Tpi4YFeM7VHcq6FWtp947NL5Cw9MAO74MTHU2j+KI77TLwVRbtzDKe2Cdw5UjYeg==,iv:wqmAYGV5wK70jBRn8cZ4cwb7VFx2azAE+Xo0al6A9Xs=,tag:q5ay4WMZSnyGojha2/j1yg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:cA7uIvBbATKjDv66kOVX3KaT1R6iG+hujJ992gnohkwPkg==,iv:rxv1vxFH5ZYqewu1MoFOqU2GSZEGQShvAwWICpvlDUs=,tag:qpz7oTFglcWX7ROencpUPA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:6az4qxUJMeqU47Yroum2hXjhKrhCbSYToQJxVwpO4w==,iv:FJtZ8hK+p7jMcUx7lC88Rk1fvokXW/H9GtG8KsrTCCk=,tag:P0GZyS+PNxZ7+ol0n8DyzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z0VOMGJCeVVMd2tCRHph
            QWpwaytVSkZNZTVRR01uNXhWMWJzT3lKb0ZRCmxQTGdKeldJTU1UMGVTTk9MenBL
            MFdPajEyTkIwY3pna052VE9HR0hrTU0KLS0tIFArVXZmUTVTQmRXaGJReXgwOFkr
            cWZMSkdpRjVwZThLUzltQ0twSXllbUkKGlHwgLTlDVhnsS4QB7cPppe6qjD1+h5L
            NNMyLq8xie/Zwbo0Wco0+sVBeVL5hNUog77o/B2wuGDrs6wJMF9Uvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:18:36Z"
    mac: ENC[AES256_GCM,data:1sYKV6dg1iOBPhjO2734t/Kz/G2/6WCMno140RdMow4j2ipzuJkhkivsQN6GlJmvYVbHllAN7w2tUTZzUac5j/FsGH2L48Xxh6AWI7p3tSIo5In4ODgRbWSbAHgIWxgz8976MA0Ss3Hr0/nGNEkTGmyC/JcrLCqq1qfsTD25Zp8=,iv:0KztBblk8lRT73dQA8v83OfOR6lOevO9nhrWE3vcAlE=,tag:a73LqrIuqzxd/LWZCjn48A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
