apiVersion: v1
kind: Secret
metadata:
    name: vitasync-secrets
    namespace: vitasync
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:2QW9nktqKaMDjXVnhfafN8qRcwm5Z8rfjUsp7HROCqIyqKzMMXHwXaWWdclrent9DU9cS5Sp8qaamgjB+XMy2Q==,iv:6V6qorREaBDxK8abqUK2n6B3VUUCNOe6y4/mWdaLZso=,tag:EVHT6Dm3IOC08d+WfYfMug==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:SVh4KirNkWv6iy5XBrdRlqWFbARIRmb74ZKZ1W8ahbLcYBy3POOcY8QsMErVFVixXaHubFnBfgWyKeC5bGGkdA==,iv:c929EcBlRCRnvDaqDBcRckfhWo5iUvxlEoXj6YBr9fg=,tag:jLumdLtwVsC35u2Qw4uoAA==,type:str]
    ADMIN_API_KEY: ENC[AES256_GCM,data:oIOVWhMaR8434P+SgTjrJ4X0dFhBpr5MG6ocHRedXH2UBOCYh5Lt32n/8Xsx4joV,iv:j/2nJAJwlIueeGAG8YltFEdRJa/CHe2l0/zM64XLHXw=,tag:QTZgCoPPHVH6MBHPCm2ZZw==,type:str]
    NEXT_PUBLIC_DEFAULT_API_KEY: ENC[AES256_GCM,data:soHXEhvxndo0UCgx1k+0ClWf0iwhur0TdRQPuyWIUnWBfiOTZt8xCw==,iv:LJlus6iesQao3thmeYNtEp6D8v4Y/q0bT4zPGqc3tNY=,tag:zVhRZE61imDWMzZXC4JK/g==,type:str]
    WHOOP_CLIENT_ID: ENC[AES256_GCM,data:qJZJSxCOO8RnEDeTJclGqxyhZ7LFuUnVNSigu0HxR4qXeX20,iv:kCxnQ9u7KJ4zgY+fLSz6348OePS4QCZBosq1z7i2Mb4=,tag:2qX7kSbp23Xmra7E+oztGw==,type:str]
    WHOOP_CLIENT_SECRET: ENC[AES256_GCM,data:3WztlmoLpioXGM7IKGF9eezQlnQBRYpoCQrvqo+q6uq42NAjbKJ9vTavpGDuExCufAL4AtKCIN2DVMd9mC470Q==,iv:xe46dwO84fjpr26WR4nSq5DjF0/30fQzg3p9CqPKBu4=,tag:UaHLYsj7dkG81VSoR74X9g==,type:str]
    WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:O4dnEePjpUVpC733xsR6nPqfjyQleak0Xx/gvWSeHanodt0c5Sei4shwQZBopryA0FLJHYkd+66Iz3JISm3FRw==,iv:pyTb7CO65vf9AK0r3yEDOS6ubnHk4d3vgMpscxAWEwg=,tag:njkdO0vIPMv453qjA4m1eA==,type:str]
    WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:dyLaY9rOAC54RZc+ZJpZXoT8YLqiwzHWTZqIPBEXSzrTy+A6qGWqbw1OSOFU+hRVqarE+ayOwrVQQ3aUANnh6A==,iv:/OdJ4CpFSyWxVnS18CfhCzqyjZwABQxQiTicPBwKM5Q=,tag:ErZ5nfvLuhN3ciZ+1EWflA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:ueYykD2egdVPT9Xc/FPRn+R+mMzantrMfxs0WeoQypdp2w==,iv:hAdppTXaMNv/n+f5ZDtpdZtN86pwU9yzgc3MsxkXqIE=,tag:zkrzFc368OVLpNUwEDBLdQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LiwIuFdoIaHjlxIKFCwFDMQ+F/FToIOm/xGSwdYwdieve3DjBCpO6wwXkDGzWAquTVqjPiyyRxEpfatFvvCjVbpvhkjAtRmrXq0kx72FtKDyy5SjnklPU5IKoIh4CUoV1LqpBq9OamCT1doUodvvms/D5jfAp5qGHKdm/yY=,iv:XXvZB8aC3BW6+6C5N6WuyHT+xC2b7StckJOxQ/3JjPo=,tag:OsIYK34tzmqx886CvkEOIw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:fPQbZxmscsZV3pdymfGWZArF+6wvbmEVjlEWO7pNfQ==,iv:Uo+rOYKYCRLdE6farZf14M8oRxJD2ln5bbRsCeWz4d4=,tag:DX2mzzGjif/51pLFNP+6sg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:NQMy71c++6gAc9WjK4HbAVGF1UbfuojLtcDX7u+Cjy3imsoHdVIYRHIqu3f+8SsfP6SDeQURaKnWHMqKsPIVJtKsHNw8ZX7E3033qqiy6xcT5g==,iv:cVeVe5yXLaqLj//vYdIRzCU9YdYYGntteN0T7UXZOmQ=,tag:X+Y+TSbj6E6syoyKL/leqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb0RIaFZ4cEdVU2FCR1pB
            eWp0bXorR092aElmWEdkYnpETEdjVVc2L1g4CnlDUW4yN0pjU0U3c2ZTa1RoSmdK
            b1FteGNrcnFLbWJnd1ZGL2tUbU5vekEKLS0tIFdVc3Z3QXNOS2VIRndESUhLZGx0
            RWdHWFVablYvd0NWaENBWi9ZSW9xeEUKY5by6lhDs/hMr9lSlZmLWs3FIcIC5guI
            D5zlZqAO6y8SLLhyBtz/2jmgbrCCdkY+/SUC3RQng49J38FiJGUzDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T13:19:34Z"
    mac: ENC[AES256_GCM,data:794rvB31aCALKXctnk/l0PpsMofvY1pI+xAzfw/Gg0zHLweN0dhm4MiKNR0PtD48/2pZCQEdkct7gVGB1IxuG2p79n4lT08tMHY++D8QLtEkuBl76I5JqlruJKZGggDXzBy2wmnKmG96hAz2DTC1AWzkKVu7kJOTFyq8bnLRcGU=,iv:z+PGbdEOlKosF+n6ihn2+ym7EY+N2zbiwQR7MShE+v4=,tag:Wp1OQqoAwJjSLnoRbaS3Mg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
