apiVersion: v1
kind: Secret
metadata:
    name: vitasync-credentials
    namespace: vitasync
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:2BEZu3L2M3rcKQf2npsdykW/vHGJ1v4AAgFEcvT7W6HYmaYRyxw3730JDKEQN0DH7gNXeaeNAl/rH5RAm+rWtA==,iv:U1mo5FXVia1alDitaYNLAvIDg5Z4uzvILDKHH3YXkqA=,tag:45RRMOWLZw4CrWzHxU+CUQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:fUlQvD+pbQUcCdAj65f44DP5OgqFKs/r1dtGXs377aO3ZbZIs7tL/nhI3HcMgijax6/FB6UMLHYPz4f/QPYL7g==,iv:c8e3hymz2OFB/PyRii9MKijbiDsGwi1leY584zwMmQs=,tag:oUf7eHFvIdMtdqHfN36yGw==,type:str]
    ADMIN_API_KEY: ENC[AES256_GCM,data:rzHkuQrZnWNMSxjUd1aIoI1niGEtgOc1lEEtkFLN8FyzdBPo1FhxZhoQ9XW2Dgzq,iv:2Tiz3yMcfvF7OxdxJZCkCdO9pYieW3zfk7rxUJ7SvK0=,tag:fjvoeOdtZuxkdDYgv1OjvA==,type:str]
    NEXT_PUBLIC_DEFAULT_API_KEY: ENC[AES256_GCM,data:XBm2wOdEZSSDsIPGYR+03KGiLE9T/j8lOiUN/gJowA7qmWBp4Qtziw==,iv:Q3yonwBRXWAxbnHgpIiPEG7gAFkKc3bXeClOY/E5lRw=,tag:ssMXKTZ7ybatuv2iQrcevg==,type:str]
    WHOOP_CLIENT_ID: ENC[AES256_GCM,data:SNrvNzD1xR0haiaGUUFqkc6L1pr1UNDugLLT5MBDa9naHkPi,iv:TOqkuk83488v1Mf6vKGUCNNWMyQ4vBnv4IFb3y0VC/U=,tag:FTJFYW4zwzbCzR3zMh3V7Q==,type:str]
    WHOOP_CLIENT_SECRET: ENC[AES256_GCM,data:84K3cCUqFBUCDpwm8MpbVRb4CyzA20anTvVK8URC0EnTUAwQpOd25UHFkFA2AXCMB3AQV5tGp/IauNDv4mgwDg==,iv:yugGzsYoAJLsMEAYts4nmKnUwbc9Rg3Wi1AHHe+ujtw=,tag:VyDZuGHs96ftN2wjbmmRKQ==,type:str]
    WITHINGS_CLIENT_ID: ENC[AES256_GCM,data:fCxKS+ICI0w8KUbTkGRXnhaZzKC704QQeR0WxUlrSSbukDafdVKfwtRJVn4oTibW1wqCvHwAAkRjLdNJQshnww==,iv:DFlCSyRNx66gE5KpomZ8Xh/JZXDI68fYu0isKk28/m8=,tag:dBHXVe0/6WP5+ytnmdzuDg==,type:str]
    WITHINGS_CLIENT_SECRET: ENC[AES256_GCM,data:TZpVpVX9VdGG+64ZD2OXFSFe54huCkd13Yep0oXSwiyRpOOWggn82udS/WxIO2R/AQxAN24GbSeI71E7YTwmHg==,iv:/g/oz02O1fCCXuDy68jz97xuplynOY/Ds8ufFFSbfi0=,tag:s4Y3yaM2/4rTqwthbjO9RA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:RrIQF3TAA2kHbLvsQl6catrJEMrSPsyOnk6yubDg3EoSeA==,iv:lHr50Esl8/CI+HYuExguEQOJltee+ihcl/P/Jwi3g8c=,tag:R+FcwQfOLhNiemR0e7yWFg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:Mj7WnOcTi0xlbhzysmIyTSuLuikjjHZQ1pAL1MoCGA==,iv:LPcp2rs7x5lFKYBismCBNv2OEsUJwqUzN7St6CCSX94=,tag:CwOqKy9LJF8hTvOeaWu2XQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCdzArdWt4MTRDejliRkVu
            WlBnVVUwdUM0UU5hTmc3dTlSNmJYTG40MWowCk9nWmk4RVE5eU1Ia3VsLzRsU1VY
            VkdKK2xmem5wdVpHZUg2bUhVKzc1Mk0KLS0tIEdlK0ZPaEtKa2dQT0Fpc1VncHRm
            WUxuVlIydTU1bG1yTGhqdjh4aFY2L2MKeSGogkvneDsUiKZrQ16D5k1rQ0dz5sj7
            u5Osyv/lk49bKi7euLBV6KNIEXCxpI8+8jcjYDwVPbeJQjhmFZ+/Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T19:39:07Z"
    mac: ENC[AES256_GCM,data:gaKoZRqBxpY8GAVg/R+RdEEmgcZQXUCWz/u0QH0YDC+9fZm1SWX+T3QOPwRiTNmUliQB1pkv03FEdc+j3wzK71M6jd/m3Fr0n2wfSep1cDeDrbFovo6apNSV167o1XOBPe7Ase4whG9j1Mc4Ep1qqfVJ/nQzjGaXq9qelcGU/IE=,iv:hkfc080+z7jG1hT7ISNMxfnjKVJUOKO5Ab9xPgS/NGY=,tag:dilCZCEsOHCqX3fQjVuA6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
