apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-media
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-consume
  labels:
    app.kubernetes.io/name: paperless-ngx
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
