apiVersion: v1
kind: Secret
metadata:
    name: mongo-express
    namespace: mongo-express
type: Opaque
stringData:
    ME_CONFIG_MONGODB_URL: ENC[AES256_GCM,data:LJryNf+MGyvFaTAbwNS0fFQbr3oen1yw8quPjFk0VMw0EshcxgBXw1baRJtRC8RFBPmlYfbgAVJ2hg7Ml1T46Ha0S7Kroxltoe6C3aA99vKWYl2dj0D2,iv:JjpzB8g1SwQn8sZKUItEiYqQAWfwh2VbmXj9CRnXODU=,tag:r2w3aBp+176orpBTntynVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aE95TEV1YlZuMGxsdzNX
            d3pGV3U3VTBNaThrTit0QUZDN0gzRGZSVzBzCjRnbHZjVlg2NzI1dDhzNDc2L2J2
            WGgxcmlGSUxvZFhtU0h0Y2ZFN1M3RkEKLS0tIENCcTU4bTgxQ05MZDVkSGQ4bzFn
            QlBuc3lTUEZsZ01obk1LSU14ZTNiL2cKLVGN6W5KzHtiFrTqQB+7ikcnHRA6tAis
            /P8TJvw0xFQoSd1O0rHLnstPwbOcLdlnkecUuE8aP7iFDLHNQZfO3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T17:53:35Z"
    mac: ENC[AES256_GCM,data:MB9chsJxJCTnMmnm20tyoRtnfrf41w0L9s2BEdxi7uF1mVNhVxeL1rKCXxsnXOTWA9p359QQ4xFvcCLuff8zIqFQ5HNBMEkVp92W4PZwkk+5ZrkWb1Y1JIY7Y2JHtT4nJxvN4CXQ7wBEyjSq3sGb+9dinQJ7lchBl+YPu7k83zQ=,iv:dsr0LmC/hvJiD9c4BCB4y5lVC9fzPcXDfwGcjSIyYQs=,tag:kDIeRVgN9SiGcKWACJVBxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
