apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2fauth-data
  labels:
    app.kubernetes.io/name: 2fauth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
