apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twofauth-data
  labels:
    app.kubernetes.io/name: twofauth
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
