apiVersion: v1
kind: Service
metadata:
  name: portainer
  labels:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: http
      nodePort: 30777
      protocol: TCP
      name: http
    - port: 9443
      targetPort: https
      nodePort: 30779
      protocol: TCP
      name: https
    - port: 8000
      targetPort: tcp-edge
      nodePort: 30776
      protocol: TCP
      name: tcp-edge
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
