---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    tier: monitoring
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "8.*"
    helm:
      valuesObject:
        admin:
          existingSecret: grafana-admin-secret
          userKey: admin-user
          passwordKey: password
        envFromSecrets:
          - name: grafana-smtp-secret
            optional: false
        env:
          GF_SERVER_ROOT_URL: https://grafana.cyphers.app
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: http://authentik-server.authentik.svc.cluster.local/application/o/token/
          GF_AUTH_GENERIC_OAUTH_API_URL: http://authentik-server.authentik.svc.cluster.local/application/o/userinfo/
          GF_SMTP_ENABLED: "true"
          GF_SMTP_HOST: smtp.sendgrid.net
          GF_SMTP_FROM_ADDRESS: grafana@cyphers.app
          GF_SMTP_FROM_NAME: Cyphers Grafana
          GF_SMTP_SKIP_VERIFY: "false"
        persistence:
          enabled: true
          existingClaim: grafana-pvc
          size: 10Gi
          storageClassName: longhorn
        service:
          type: ClusterIP
          port: 3000
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
