---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-resources
  namespace: argocd
  labels:
    tier: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/atulmgupta/-k3s-gitops.git
    targetRevision: main
    path: apps/grafana/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
