apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  annotations:
    kubernetes.io/ingress.class: traefik-external
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "IT Tools"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "it-tools"
    gethomepage.dev/description: "Developer Utilities"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`devtools.cyphers.app`)
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: authentik-auth
          namespace: authentik
      services:
        - name: it-tools
          namespace: it-tools
          port: 80
  tls:
    secretName: production-cyphers-app-tls
