---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    tier: monitoring
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "82.*"
    helm:
      valuesObject:
        grafana:
          enabled: false
        prometheus:
          service:
            type: LoadBalancer
          prometheusSpec:
            retention: 7d
            retentionSize: 100GB
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 250Gi
        alertmanager:
          enabled: true
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  resources:
                    requests:
                      storage: 8Gi
        nodeExporter:
          enabled: true
        prometheus-node-exporter:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node.kubernetes.io/unschedulable
                        operator: DoesNotExist
        kubeStateMetrics:
          enabled: true
        prometheusOperator:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions: [.spec, .metadata.annotations]
    - group: monitoring.coreos.com
      kind: Alertmanager
      jqPathExpressions: [.spec]
    - group: monitoring.coreos.com
      kind: Prometheus
      jqPathExpressions: [.spec]
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
