---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-resources
  namespace: argocd
  labels:
    tier: database
spec:
  project: default
  source:
    repoURL: https://github.com/atulmgupta/-k3s-gitops.git
    targetRevision: main
    path: apps/redis/resources
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    syncOptions: [CreateNamespace=true]
