apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: pgbouncer
spec:
  type: ClusterIP
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
      protocol: TCP
  selector:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/instance: pgbouncer
