apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache
  labels:
    app.kubernetes.io/name: ntfy
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
