apiVersion: v1
kind: Secret
metadata:
    name: teslamate-teslamate-secret
    namespace: teslamate
type: Opaque
stringData:
    DATABASE_NAME: ENC[AES256_GCM,data:picmrcvazd8G,iv:pw9xym+llSwKE0lh8tltTABHjaNAOgvoxRpR1qYRc30=,tag:8p8VruYTSQYE7IVo+QT0bw==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:k9zWii/avoad,iv:18lxfmIjPEOxjjfjer4UbbYGDQM6zhP/avnCJa/9ptU=,tag:bgpH3f6WKRYgWdvpgpky7g==,type:str]
    DATABASE_PASS: ENC[AES256_GCM,data:+va6bfHDl6CMA++HB/pHPsoPwqz/73J7i9FXKVYEGvaTV+u8fK4by+BNcqI=,iv:If6d8NenD/bOgIDETh65pLyrTkJIACwdeylJgnE/5SQ=,tag:krNR9IMtlIB+YviYycATVg==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:P8VZNiws5ITpA7N1J8GG6nBYAllAugf2blztL3E=,iv:wI6S0R7UTuYcjFcvQ0Tf/Oj5Ms8HMfI0hRIVMv0rCLM=,tag:zIYkTyvBi/n+08TMLcBdFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nqt7rptevevv0se64ryupta6zpdr4zzh9rhg4aec9xfqhsyw23cquqzrj0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSk1aOW5XY0FmeGpCVVli
            THBrS09VWVRYREJsUFBrYzhMWFNiYmZiYUVVCnBVaUNmdVRJWGVtNnd1QmZ6ZnJy
            NEloNmxTVXVybW84eEp6Tm5jaVdmeVkKLS0tIENtbHVsWlBUWmVnaW5yaThpZGRN
            WFZqbXVNK29LdXlyV2p1YnZhSk51MDAKJnQamFFjlksKXj/PvXtXUghPNPrjGzn0
            ZrCYg1FrEDxMiM08jGv+j1914/wFL3gA4z5GLvB1TqCtjojt/QKMKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T12:59:34Z"
    mac: ENC[AES256_GCM,data:Emr7vzTazL5aOnvngxLAjMkz/ZBfuL3YDYikO3B2tu7tleq8oDY8rO1Qaf5/FfiUyx3Jfkiq3w0O10gsCeHSbDI1G2L2OF9RudSqSyg6x6Vpp/8nuLlOrJsMAF0dzaCsruc2uiy2U4NL9dbNuXXm/p8ttX9qVkdrtGKVXAvZg4w=,iv:PloPkRKPci2Vgk+sJKdazdCjo1AMz71RwXN3hMbDTXo=,tag:UyQDPQkjsH9HkuqYNx1fvg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
